### ISSUE TITLE
Question about repeated CV in Caret

### ISSUE THREAD

**Issue by Nelhachem** [topepo/caret#1028]
Hello,

I am new to caret and I have a quick question:
From my dataset:
modelA

137 samples
13 predictor

No pre-processing
Resampling: Cross-Validated (10 fold, repeated 5 times) 
Summary of sample sizes: 123, 123, 125, 123, 123, 124, ...

Why different sample sizes? Any nice explanation how repeated cv is working here
Thanks

**Comment by BU-1** [comment]
10 fold 5 repeat cross validation splits your data set into groups of 10, 5 separate times. Since 137 is not divisible by 10, each fold will have a different number of samples (e.g. Fold 1 could have 13 and Fold 2 could have 14). So if the out-of-sample fold has 13 then the sample size (remaining 9 folds) is 124, but if the it's 14 the sample size is 123.

**Comment by Nelhachem** [comment]
Thanks. very informative

**Comment by vinayvrv** [comment]
So in Repeated CV, i.e 10 fold 5 repeat cross . Will the data sample ( resample ) be different for each repeat? E.g say for the first time repeat we take index [19,24,32,44,55] and for 2 repeat it take [11, 9, 5, 23, 78] Is there a way to check what is actually going into the training every time?
