### ISSUE TITLE
Unnecessary call to predictionFunction when using predict.train with type="prob"?

### ISSUE THREAD

**Issue by matthuska** [topepo/caret#105]
I noticed that when predicting class probabilities, the classes themselves are predicted as well as the class probabilities (from extractProb.R, lines 98-105):

```
      tempUnkPred <- predictionFunction(models[[i]]$modelInfo,                                                                           
                                        models[[i]]$finalModel,                                                                          
                                        tempX,                                                                                           
                                        models[[i]]$preProcess)                                                                          
      tempUnkProb <- probFunction(models[[i]]$modelInfo,                                                                                 
                                  models[[i]]$finalModel,                                                                                
                                  tempX,                                                                                                 
                                  models[[i]]$preProcess)    
```

In the case of the model I'm using, this makes prediction take twice as long as it should because the prediction is performed twice. Is this on purpose or is it a bug? Couldn't we accomplish the same result by only calling probFunction, and then using a cutoff to determine class membership, and save a lot of runtime?

**Comment by topepo** [comment]
There is no functional reason to have the class predicted too; that's just how I wrote it so I wouldn't have to call the other function. I'll make a change for the next version that will add an option to estimate the class predictions. 

Believe it or not, there are some models where the class predictions and the probability predictions disagree. At this point I've probably error trapped them or base the predictions off of the probs so I will just choose the class with the largest probability here instead of calling `predictionFunction` again (as you suggest).

**Comment by topepo** [comment]
Checked in and tested
