### ISSUE TITLE
Using recipes with caret

### ISSUE THREAD

**Issue by Ronen4321** [topepo/caret#1074]
Hi,

I need your advice.

I used the caret::train with a recipe, one of the steps include step_pca.
Next, I prepared the recipe and baked the test data.
Upon prediction on test data the caret::predict function compliance that some original variables are missing.
To my best understanding, the only way out is to bake the train data and let caret::train fit the baked training data.
Is it correct?

Thanks!

**Comment by topepo** [comment]
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please help me help you!

If you've never heard of a reprex before, start by reading "[What is a reprex](https://github.com/tidyverse/reprex#what-is-a-reprex)", and follow the advice further down that page.

**Comment by Ronen4321** [comment]
It was some misunderstanding at my end.
