### ISSUE TITLE
Why does `predict` glmStepAIC requires dropped variables in newdata to work?

### ISSUE THREAD

**Issue by asiripanich** [topepo/caret#1082]
https://github.com/topepo/caret/blob/22cdd34644a5d445ccec16bee3e55fcf015c42f4/pkg/caret/R/predict.train.R#L125-L129

Failed to use `predict` on a `train.glmStepAIC` object with a dataset in `newdata` that only contains the variables used in the final model. I'm unsure why `train` keeps `terms` and `xlevels` of the full/initial model instead of the final model. Whereas, the `MASS::stepAIC()` function keeps `terms` and `xlevels` of the final model. Is this a bug in caret? 

Thank you :)

**Comment by topepo** [comment]
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please help me help you!

If you've never heard of a reprex before, start by reading "[What is a reprex](https://github.com/tidyverse/reprex#what-is-a-reprex)", and follow the advice further down that page.
