### ISSUE TITLE
multiClassSummary Help

### ISSUE THREAD

**Issue by Kasmodean** [topepo/caret#1209]
Sorry, my background is not in coding.  Is there a way to get multiClassSummary when used in TrainControl to output the precision of a specific class instead of the mean?  I am usually good at getting my coding done by googling for examples, but I can't find many examples for multiClassSummary that help me.

Thank you.

**Comment by topepo** [comment]
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please help me help you!

If you've never heard of a reprex before, start by reading "[What is a reprex](https://github.com/tidyverse/reprex#what-is-a-reprex)", and follow the advice further down that page.
