### ISSUE TITLE
investigate sgd

### ISSUE THREAD

**Issue by topepo** [topepo/caret#152]
[here](http://cran.r-project.org/web/packages/sgd/index.html)

**Comment by topepo** [comment]
Added a card to the [new models project page](https://github.com/topepo/caret/projects/2) instead of using issues.

**Comment by hadjipantelis** [comment]
I was looking into `sgd`. It seems very nice and I would like to help adding it to `caret` but a couple of design questions do arise.  

1. `sgd` takes two separate "parameter" arguments. One for the model control (`model.control`) and one for the optimisation control (`sgd.control`); `...` arguments are used to form default `sgd.control` arguments if it is not supplied directly. That makes the interface a bit peculiar because the users cannot easily access/set certain parameters.  
I guess the obvious `L1` and `L2` arguments will be what `caret::train` will optimise against  so that means caret will optimise "model control" parameters and leave all `sgd.control` parameters to the user? I suggest that but I am open to other suggestions.
2. Aside inputs for class `formula` and `matrix`, `train` will also have to accommodate `big.matrix`. `big.matrix` will convert factors to numeric via factor level numberings. Should there be a check/warning about that? (eg. "`y` is `big.matrix`, this is only valid for regression tasks.") Otherwise `big.matrix` seems to work mostly fine (tiny example shown below).

```R
devtools::load_all('git_projects/original-caret/pkg/caret/')
# load the iris dataset
data(iris)
N = nrow(iris);
set.seed(123)
testIndx = sample(1:N, N*0.33)
trainInx  = c(1:N)[-testIndx]
library(bigmemory)
iris2 = as.big.matrix(iris)
model01 <- train(y = iris[trainInx,"Species"], x = iris2[trainInx,1:4], method='ranger') 
  # Using `iris2` instead of `iris` for `y` in `train` will result in regression.
predict( model01, iris2[testIndx,1:4])
```
