### ISSUE TITLE
Random search for hyper-parameter optimization

### ISSUE THREAD

**Issue by ck37** [topepo/caret#186]
It would be nice to support random search for hyperparameter tuning. Here is one good paper on it: http://dl.acm.org/citation.cfm?id=2188395

I think it would be a great complement to the standard grid search and the new adaptive search options.

**Comment by zachmayer** [comment]
Paper here: http://jmlr.csail.mit.edu/papers/volume13/bergstra12a/bergstra12a.pdf

We could potentially achieve this by creating random grids for grid search.

**Comment by topepo** [comment]
I'll add this to the next version. 

Right now, you can create a random matrix yourself and pass it in via `tuneGrid`. 

I've never really liked that paper for specific technical reasons (i.e. grid search and manual search can take the same amount of time) but more broadly since they assume that what is good for deep learning is good for everyone else. They also "stack the deck" when it comes to their problem by adding everything but their shoe size to the list of tuning parameters. 

Keep in mind that:
* the average number of tuning parameters exposed to users via `train` is about 1.6 (across 192 models). About half have either no tuning parameters or one. 
* the "sub-model trick" can allow you to search a dense grid without much of a penalty for a lot of models, especially boosting. It may be more computationally taxing to do random search since it might disable the ability to do this optimization. 

That said, it is not a big technical problem and I can probably get it done in a week or so. 

Thanks,

Max

**Comment by zachmayer** [comment]
We could exploit the sub-model trick by adding dense parts of the grid back in.  E.g. the random search chooses 382 trees in a GBM, and we add the 1-382 sub models back into the grid.

It would probably make sense to limit the number of sub-models, e.g. 1-382 in increments of 50.

**Comment by topepo** [comment]
True, but this happens for unique combinations of `interaction.depth`, `shrinkage`, and `n.minobsinnode`. If these parameters are randomly determined, there is a low probability of hitting those more than once. 

That was the first model I implemented for testing...

**Comment by topepo** [comment]
I just committed a large number of files for this. Please take a look and comment. The man pages are updated but there will be a [new html page](https://github.com/topepo/caret/blob/master/html/random.Rhtml) with a simple example and the usage.
