### ISSUE TITLE
Getting Confidence & Prediction Intervals from predict.train

### ISSUE THREAD

**Issue by wmurphyrd** [topepo/caret#187]
It is not currently possible with `predict.train` to request confidence or prediction intervals via the underlying `predict` functions of models (for those methods that support it). Calling the `predict` method on the `finalModel` is not straightforward because the predictors need to be pre-processesed and in the form of a design matrix.

Supporting intervals via `predict.train` would require the following:
1. Modify `extractPrediction`, `predictionFunction`, pass `...` arguments down to the `predict` function in the model definitions
2. Modify `extractPrediction` to handle prediction results with multiple columns
3. Modify `trimPredictions` to handle 2-dimensional data
4. Modify `predict.train` to return those extra columns when present
5. Modify all model definitions to pass `...` on to the model's `predict` function

I have completed 1-4 [on my fork](https://github.com/wmurphyrd/caret/tree/PredictionIntervals) and am working my way through 5. Additional effects of these changes are that other optional arguments to the model's `predict` method can be specified and the `param` argument to `predictionFunction` can now be passed to the higher level functions in order to successfully retrieve sub-model predictions (not sure if this is valuable to end users). 

Concerns: 
- Not all model's `predict` methods utilize optional arguments, but it seems easier just to add the dots to all of them (since no harm will be done) than to look up each specification to check
- Some model's caret definitions retrieve specific variables or columns from the predict function result, so requested intervals would not make it back to the user (unsure if any of these actually support intervals; may be moot)
- Requesting both sub-models and intervals would result in 3-dimensional data that is not supported by the modified `extractPrediction`; I haven't identified any model methods that actually support both options, but planning to add checking and error message just in case

Alternative: Could add a `prepareOnly` optional argument to `predict.train` that would return the prepared `newdata` instead of the predictions so that the user could then call `predict` on `finalModel` with whichever arguments were desired. It would be a simpler update, but less user-friendly experience

Let me know if this is something you'd be interested in pulling, and I'll finish the model definition updates and add unit tests

**Comment by zachmayer** [comment]
This seems like an excellent idea.  If you add unit tests, I'd vote to merge it in.






—

**Comment by topepo** [comment]
I think that this is a good idea but it does make me a little nervous, especially the parts where `predictionFunction` is impacted (or anything inside of the workflow functions). 

It might be a good idea to restrict the interface so that it can (mainly) be accessed via `predict.train`. I've had a few requests to return a multivariate prediction in the past and, once I looked around, it seemed like an invasive change. 

Also, it would be difficult to support people using this functionality inside of the model internals that define the methods and I'd like to discourage that. 

So... I'd say "have at it" but we're going to want to test it a lot and make sure that it doesn't complicate the underlying code to a large degree. I have another package (that will remain nameless) where we tried to expand functionality and it eventually doomed the whole thing so I might be a bit conservative about big changes to the core parts. 

Thanks,

Max

**Comment by topepo** [comment]
So, does passing the ellipses through `predict.train` the only thing that you had to do to allow passing `param` to the underlying predict code? 

That is interesting, but I'm not sure that I want to support that as a feature especially for methods where we exploit sub-models. I'm okay with being _able_ to do it, but I'm apprehensive about putting it in the man page since that implies that it is a supported feature.

**Comment by wmurphyrd** [comment]
I definitely get your concerns and understand it will be up to you for the final decision after it's complete. I've aimed for minimal changes and taken great care to ensure functionality and return types for existing usage aren't altered. I'll also provide thorough unit tests. 

If you prefer, I could restrict this to only let the `interval` argument pass through to reduce the opportunity of using this to mess around with model internals.

For `param`, the ellipses pass through was all it took to be able to request it, and it just took a little tweaking to what I'd done in `extractPrediction` to be able to handle lists coming out of `predictionFunction` in addition to vectors and data frames (that particular step is going to get some error handling just in case the list components come back as something other than the expected vectors). I had added some info about param and submodels in the docs, but I'll take it out.

**Comment by topepo** [comment]
> I had added some info about param and submodels in the docs, but I'll take it out.

That's probably best. 

This does lay the groundwork for some changes to use survival models that I will start on soon, so it is worth doing. Thanks for taking the initiative. 

Max

**Comment by Bijaelo** [comment]
This issue never seems to have been fixed as suggested by @topepo or @wmurphyrd back in 2015? 

A less invasive method might be to implement a function, allowing one to create `newdata` with the appropriate shape and names to use with `predict(object$finalModel, newdata = newdata)`. One question on SO [(here)](https://stackoverflow.com/a/58016929/10782538) prompted me to look into the issue.  The answer contains a function specifically for `train(..., method = "lm")`, using the internal body from `predict.train` `predictionFunction` and `object$modelInfo$predict` of this output as a baseline, converts `newdata` to `data.frame` if `as.data.frame` is found in the body of `object$modelInfo$predict`, while also preprocessing the data if it would have been preprocessed by `predictionFunction`. 

I am not certain how if any other kind of output compared to `as.data.frame` is used, but this does seem to be a very small and less invasive addition to the caret package.

**Comment by topepo** [comment]
This is a good idea and is implemented in `tidymodels`. 

Unfortunately, `caret` is at the lifecycle point of having a fairly complete interface, so this isn't a good fit.  

The development work is focused on squashing bugs and any changed required by the underlying model packages.
