### ISSUE TITLE
Are kappa or overall SD reliable measures for visualising them on bar plots? 

### ISSUE THREAD

**Issue by acocac** [topepo/caret#215]
Hi,

I am interested to generate bar plots that show several best models with error (standard deviation). In theory, the average bar + error mustn't be greater than 1, but when I am plotting them they are greater than 1. 

I just wonder how can I extract model resamples of each best model just to check how the standard deviation is generated. Additionally, I would like also to add others statistic measures such as coefficient of variance, standard error, among others.

**Comment by topepo** [comment]
> In theory, the average bar + error mustn't be greater than 1

True. It might make sense to do a transformation of the values and compute the interval on a different scale to get an asymmetric interval. Since Kappa is on +/-1, I'm not sure that that is though. You can also truncate the interval at 1. 

Also, you can save the resampled performance values using

```r
   trainControl(returnResamp = "final") ## or "all"
```

From there, you can roll them in any way that you like. 

Thanks,

Max
