### ISSUE TITLE
consider moving `metric` in rfe() and sbf() to the control function

### ISSUE THREAD

**Issue by topepo** [topepo/caret#24]
So they do not conflict with the same option in `train`

**Comment by lcougnaud** [comment]
Has this issue been fix?
I would like to use another metric (ROC) than the accuracy to optimize (for feature selection and parameters tuning of the method) in rfe (with `caretFunctions` used as function).
Setting metric to ROC results indeed in the use of the ROC for the parameters selection, but accuracy is used for parameters tuning (and especially for the final fit), because the 'metric' option is not passed to the `rfeControl$functions$fit`, so here `train`.

Thanks in advance!

**Comment by topepo** [comment]
This would break backward compatibility for a lot of code. I have a few other changes that would do the same and I'm saving them for a single release. I'll estimate that this will happened in the first 2-3 months of 2017. 

For now, you can write a custom method by altering the functions in `caretFunctions` so that they use the method you desire.

**Comment by lcougnaud** [comment]
Thank you for your quick feedback (and your time estimation), I will use a modification of the `caretFunctions` for now.
Thanks again!
