### ISSUE TITLE
Data imputation

### ISSUE THREAD

**Issue by trufanov-nok** [topepo/caret#292]
Hi,
I would like to use caret for data imputation. As far as I understand, I can use `preProcess` function for that. The problem is that its result can be used in `predict` function only. But I would like just to fill in NAs in my dataset and save it it a new file for further use in 3rd party app. So it seems caret's imputation can't be used as feature by itself - it's just a part of caret's prediction procedure.  
I'm I right? Is there a workarounds to get sensible results from preProcess return value to patch dataset? Is there any plans to make data imputation a more independent functionality?

**Comment by trufanov-nok** [comment]
Ok, I think I finally got the idea. `predict` is used to get the imputed data, not the target variable based on imputed data.
```
preProcValues <- preProcess(d, method = c("knnImpute"))
d_imputed <- predict(preProcValues, newdata= d, na.action = na.pass)
```
Would be nice to have an example in [docs](http://topepo.github.io/caret/preprocess.html#impute).

**Comment by tobigithub** [comment]
Hi,
just a philosophical comment, caret is one package with an excellent WIKI and a book, surely a big reason why its picked up by many and surely an exception among many R packages. But I agree starting with any R package could be much easier if there were more "run" examples and not so many " Not run" examples. I am also more checking the caret book and WIKI, instead of using the inbuilt help functions such as ?preProcess, even if they are OKish. One reason of course that many **native** inbuilt R function lack very good help functions, basically in many cases the R help greatly sucks, otherwise there wouldn't be so many questions on stackexchange. 

Now one could argue that reading the caret book and caret WIKI and going through all the examples would help, I agree, but truly who has "time" to do that, sometimes people just want to copy/paste to see whats going on. 

Why are there hundreds of examples with "knn" and "rf" well because these are the easiest examples and its not clear that one can simply replace "knn" with "cubist" or "earth". For  experts its hard to understand that people struggle with post-processing, with applying different methods, bootstrapping etc. However that would require to see through the eyes of beginners again. 

So I wonder if there would be an interest to create minimal **working** demos of each caret function and method. Basically a small running R program for each classification, each regression, each CV method ('boot', 'boot632', 'cv', 'repeatedcv', 'LOOCV', 'LGOCV') and each pre-processing method. In principle these examples are provided in the caret/RegressionTests/ directory but I would find the example and unit tests there rather complicated.

The two liners
````R
require(caret); data(BloodBrain);
fit1 <- train(bbbDescr, logBBB, "knn"); fit1;
````
or
```R
require(caret); data(BloodBrain);
fit1 <- train(bbbDescr, logBBB, "lars"); fit1;
```
would be good examples, because they are short, run fast, however in this case require  the BloodBrain dataset which is not installed with caret, so maybe some functions that are covered with the namespace would be better. Just an idea.

Cheers
Tobias
