### ISSUE TITLE
sparse matrices and train

### ISSUE THREAD

**Issue by topepo** [topepo/caret#31]
See [here](http://stackoverflow.com/questions/24858512/can-i-use-glmnet-with-caret-and-sparse-matrices). 

This should be feasible now that `x` and `y` are carried along separately through `train`.

**Comment by pgswartz** [comment]
Thanks for all your work on this package Max and zachmayer!  Caret's great.

I've also been trying to use sparse matrices with the output from the train method and am similarly running into forced conversion of my sparse matrices into non-sparse matrices.  I'm running caret_6.0-41 and R version 3.1.2 (2014-10-31).  If I run:

```
predict(trainObj, newdata=testSparseMatrix)
```
this is slightly slower than
```
predict(trainObj, newdata=testNonSparseMatrix)
```
Due to, based on profiling, the use of as.matrix in caret's implementation of predict. However, the following is very fast:
```
predict(trainObj$finalModel, newdata=testSparseMatrix)
```
due to, as I understand it, predict being called from the 'glmnet' package rather than 'caret'. (I know this last formulation will not carry out preprocessing, etc.).

Am I doing something wrong, or is predict(trainObj) still coercing newdata to a non-sparse form?  I did not train on a sparse matrix, using one at prediction time.

Please let me know if I can provide a toy example and thanks again for the excellent package!

**Comment by dselivanov** [comment]
@zachmayer @topepo sorry for crossposting. Can you have a look whats going wrong here: [text2vec-classification-with-caret-problems](http://stackoverflow.com/questions/38768499/text2vec-classification-with-caret-problems). How to feed sparse matrices (`dgCMatrix`) to `caret` routines?

**Comment by randomgambit** [comment]
Hello everyone,

I just discovered this amazing `caret` package. Incredible work! Following up on what has been said here, can I expect `caret` to work with sparse matrices? I am getting sparse matrices from `quanteda` after some text-classification. In other words, if I transform my sparse matrix into a dataframe, my computer will burst into flames....

Thanks!!

**Comment by randomgambit** [comment]
hello @topepo, can you please confirm caret can finally work with sparse matrices and glmnet? thanks!!
