### ISSUE TITLE
evaluate addition of mxnetr in model list

### ISSUE THREAD

**Issue by spedygiorgio** [topepo/caret#326]
A promising library for deep - learning has been recently released, see  http://www.r-bloggers.com/deep-learning-with-mxnetr/ 
It would be possible to add it to train list?

**Comment by topepo** [comment]
I've been looking at it for the last month. I had some issues getting it installed but right now I'll add it in when I have the time. If you have any scripts that we could use as a template, then that would be helpful.

**Comment by zachmayer** [comment]
I got it installed on my Mac, and Am going to try to write a home brew install script so people can install it via brew.




I have a couple example scripts we can use with train.  It's a very fast library and it works in r!



—

**Comment by topepo** [comment]
How does this look? Please test and let me know:

```r
modelInfo <- list(label = "Neural Network",
                  library = "mxnet",
                  loop = NULL,
                  type = c('Regression', 'Classification'),
                  parameters = data.frame(parameter = c('layer1', 'layer2', 'layer3', "learning.rate", "momentum", "dropout"),
                                          class = rep('numeric', 6),
                                          label = c('#Hidden Units in Layer 1', '#Hidden Units in Layer 2', '#Hidden Units in Layer 3',
                                                    "Learning Rate", "Momentum", "Dropout Rate")),
                  grid = function(x, y, len = NULL, search = "grid") {
                    if(search == "grid") {
                      out <- expand.grid(layer1 = ((1:len) * 2) - 1, layer2 = 0, layer3 = 0,
                                         learning.rate = 2e-6, momentum = 0.9, dropout = 0)
                    } else {
                      out <- data.frame(layer1 = sample(2:20, replace = TRUE, size = len),
                                        layer2 = 0,# sample(c(0, 2:20), replace = TRUE, size = len),
                                        layer3 = 0,#sample(c(0, 2:20), replace = TRUE, size = len),
                                        learning.rate = runif(len),
                                        momentum = runif(len, min = .5),
                                        dropout = runif(len, max = .5))
                    }
                    out
                  },
                  fit = function(x, y, wts, param, lev, last, classProbs, ...) {
                    num_units <- param[grepl("layer[1-9]", names(param))]
                    num_units <- num_units[num_units > 0]
                    if(!is.matrix(x)) x <- as.matrix(x)
                    if(is.numeric(y)) {
                      mx.set.seed(1)
                      out <- mx.mlp(data = x, 
                                    label = y,
                                    hidden_node = num_units,
                                    out_node = 1, 
                                    out_activation = "rmse", 
                                    learning.rate = param$learning.rate, 
                                    momentum = param$momentum, 
                                    eval.metric = mx.metric.rmse, 
                                    array.layout = "rowmajor",
                                    ...)
                    } else {
                      y <- ifelse(y == levels(y)[1], 1, 0)
                      mx.set.seed(1)
                      out <- mx.mlp(data = x, 
                                    label = y,
                                    hidden_node = num_units,
                                    out_node = length(levels(trn$Class)), 
                                    out_activation = "softmax",
                                    learning.rate = param$learning.rate, 
                                    momentum = param$momentum, 
                                    eval.metric = mx.metric.accuracy, 
                                    array.layout = "rowmajor", 
                                    ...)
                    }
                    out
                  },
                  predict = function(modelFit, newdata, submodels = NULL) {
                    if(!is.matrix(newdata)) newdata <- as.matrix(newdata)
                    pred <- predict(modelFit, newdata)
                    if(modelFit$problemType == "Regression") {
                      pred <- pred[1,]
                    } else pred <- modelFit$obsLevels[apply(pred, 2, which.max)]
                    pred
                  },
                  prob =  function(modelFit, newdata, submodels = NULL) {
                    if(!is.matrix(newdata)) newdata <- as.matrix(newdata)
                    pred <- t(predict(modelFit, newdata))
                    colnames(pred) <- modelFit$obsLevels
                    pred
                  },
                  tags = c("Neural Network"),
                  sort = function(x) x[order(x$layer1, x$layer2, x$layer3),])
```

**Comment by zachmayer** [comment]
Looks good to me!

**Comment by topepo** [comment]
Are you able to get good performance with it? I have not yet on `twoClassSummary` or `SLC14_1`. 

Can you test?

**Comment by topepo** [comment]
better for multi class and bug fix (I don't want to check it in just yet):

```r
modelInfo <- list(label = "Neural Network",
                  library = "mxnet",
                  loop = NULL,
                  type = c('Regression', 'Classification'),
                  parameters = data.frame(parameter = c('layer1', 'layer2', 'layer3', "learning.rate", "momentum", "dropout"),
                                          class = rep('numeric', 6),
                                          label = c('#Hidden Units in Layer 1', '#Hidden Units in Layer 2', '#Hidden Units in Layer 3',
                                                    "Learning Rate", "Momentum", "Dropout Rate")),
                  grid = function(x, y, len = NULL, search = "grid") {
                    if(search == "grid") {
                      out <- expand.grid(layer1 = ((1:len) * 2) - 1, layer2 = 0, layer3 = 0,
                                         learning.rate = 2e-6, momentum = 0.9, dropout = 0)
                    } else {
                      out <- data.frame(layer1 = sample(2:20, replace = TRUE, size = len),
                                        layer2 = 0,# sample(c(0, 2:20), replace = TRUE, size = len),
                                        layer3 = 0,#sample(c(0, 2:20), replace = TRUE, size = len),
                                        learning.rate = runif(len),
                                        momentum = runif(len, min = .5),
                                        dropout = runif(len, max = .5))
                    }
                    out
                  },
                  fit = function(x, y, wts, param, lev, last, classProbs, ...) {
                    num_units <- param[grepl("layer[1-9]", names(param))]
                    num_units <- num_units[num_units > 0]
                    if(!is.matrix(x)) x <- as.matrix(x)
                    if(is.numeric(y)) {
                      # mx.set.seed(1)
                      out <- mx.mlp(data = x, 
                                    label = y,
                                    hidden_node = num_units,
                                    out_node = 1, 
                                    out_activation = "rmse", 
                                    learning.rate = param$learning.rate, 
                                    momentum = param$momentum, 
                                    eval.metric = mx.metric.rmse, 
                                    array.layout = "rowmajor",
                                    ...)
                    } else {
                      y <- as.numeric(y) - 1
                      # mx.set.seed(1)
                      out <- mx.mlp(data = x, 
                                    label = y,
                                    hidden_node = num_units,
                                    out_node = length(unique(y)), 
                                    out_activation = "softmax",
                                    learning.rate = param$learning.rate, 
                                    momentum = param$momentum, 
                                    eval.metric = mx.metric.accuracy, 
                                    array.layout = "rowmajor", 
                                    ...)
                    }
                    out
                  },
                  predict = function(modelFit, newdata, submodels = NULL) {
                    if(!is.matrix(newdata)) newdata <- as.matrix(newdata)
                    pred <- predict(modelFit, newdata)
                    if(modelFit$problemType == "Regression") {
                      pred <- pred[1,]
                    } else pred <- modelFit$obsLevels[apply(pred, 2, which.max)]
                    pred
                  },
                  prob =  function(modelFit, newdata, submodels = NULL) {
                    if(!is.matrix(newdata)) newdata <- as.matrix(newdata)
                    pred <- t(predict(modelFit, newdata))
                    colnames(pred) <- modelFit$obsLevels
                    pred
                  },
                  tags = c("Neural Network"),
                  sort = function(x) x[order(x$layer1, x$layer2, x$layer3),])
```

**Comment by spedygiorgio** [comment]
I had not time to test yet, but just a question: it is possible to use "Deep Learning" as label? There are already a lot of "Neural Network"(s) models...

**Comment by topepo** [comment]
My only issue with that is that "deep learning" encompasses a bunch of different type of models that might include autoencoders and other features. The model generated by  `mx.mlp` is a feedforward multilayer network.

**Comment by topepo** [comment]
[I can't get regression to work](https://github.com/dmlc/mxnet/issues/1692) right now. Otherwise, it seems to work well for classification. I'll also add a model-averaged version (like `avNNet`) since that seems to stop it form overfitting too much.

**Comment by topepo** [comment]
The main impediment now is being able to save the `train` object and properly retain the `finalModel` component in a way that can be used later. `mxnet` has tools for saving it to a file but that's not a very good solution when it is packaged in another R object.

**Comment by thirdwing** [comment]
Just to update the status of MXNet R package.

The trained MXNet models can be saved and loaded as normal R objects now.

**Comment by topepo** [comment]
[Yes](https://github.com/dmlc/mxnet/issues/362) and as soon as I can get it installed on my mac I will update the model files ([here](https://github.com/topepo/caret/blob/master/models/files/avMxnet.R) and [here](https://github.com/topepo/caret/blob/master/models/files/mxnet.R)). 😬

Feel free to test and submit a PR in the meantime.

**Comment by topepo** [comment]
Added a card to the [new models project page](https://github.com/topepo/caret/projects/2) instead of using issues.

**Comment by hadjipantelis** [comment]
@topepo: I have been writing a wrapper mxnet that uses `adam` instead of the vanilla `sgd` optimiser, ie. different options to optimise against. It still needs a bit of ironing (and I am still not happy with the overall performance anyway) do you want a PR about it (in a weekend's time :) ) or is it just overlapping functionality with what you have so I should let it slide?

**Comment by hadjipantelis** [comment]
Hello Max,

I have made the following fork from your original mxnet model to work with `adam` optimiser. Do you want a PR about it or you are working on your own implementation?

```R
mxnetAdam <- list(label = "Neural Network", 
                  library = "mxnet", 
                  type = c('Classification','Regression'),
                  parameters = data.frame(parameter = c('nlayers', 'nnodes', 'nrounds', "dropout",
                                                        "beta1", "beta2", "learningrate"),
                                          class = rep('numeric', 7),
                                          label = c('# of layers', '# hidden units in each layer', '# of rounds',
                                                    "dropout rate",  "beta1", "beta2", "learning rate")),
                  grid = function(x, y, len = NULL, search = "grid") {
                    if(search == "grid") {
                      out <- expand.grid(nlayers = (1:len), nnodes = 25, nrounds = 50*len, 
                                         learningrate = 0.0001, beta1 = 0.9, beta2 = 0.9999, dropout = 0.05)
                    } else {
                      out <- data.frame(nlayers = sample(2:20), nnodes =  sample(c(2:99), replace = TRUE, size = len),
                                        nrounds = sample(c(10:200), replace = TRUE, size = len),
                                        learningrate = runif(len, max = 0.1),
                                        beta1 = runif(len, min = 0.5),
                                        beta2 = runif(len, min = 0.5),
                                        dropout = runif(len, max = 0.5))
                    }
                    out
                  },
                  fit = function(x, y, wts, param, lev, last, classProbs, ...) {
                    if(!is.matrix(x)) x <- as.matrix(x)
                    if(is.numeric(y)) {
                      mx.set.seed(21)  
                      out <- mx.mlp(data = x, label = y, out_node = 1, out_activation = "rmse", verbose= FALSE,
                                    optimizer = 'adam', eval.metric = mx.metric.rmse, array.layout = "rowmajor", 
                                    learning.rate = param$learningrate,  
                                    beta1 = param$beta1, 
                                    beta2 = param$beta2, 
                                    dropout = param$dropout,
                                    num.round = param$nround, 
                                    hidden_node = rep(param$nnodes, param$nlayers),
                                    activation = rep(as.character('relu'), param$nlayers),
                                    initializer = mx.init.Xavier(factor_type = "avg", magnitude = 3, rnd_type = 'uniform'),
                                    ...)
                    } else {
                      y <- as.numeric(y) - 1
                      mx.set.seed(21)
                      out <- mx.mlp(data = x, label = y, out_node = length(unique(y)), out_activation = "softmax",  verbose= FALSE,
                                    optimizer = 'adam', eval.metric = mx.metric.accuracy, array.layout = "rowmajor", 
                                    learning.rate = param$learningrate, 
                                    beta1 = param$beta1, 
                                    beta2 = param$beta2, 
                                    dropout = param$dropout,
                                    num.round = param$nrounds, 
                                    hidden_node = rep(param$nnodes, param$nlayers),
                                    activation = rep(as.character('relu'), param$nlayers), 
                                    initializer = mx.init.Xavier(factor_type = "avg", magnitude = 3, rnd_type = 'uniform'),
                                    ...)
                    }
                    mx.serialize(out)
                  },
                  predict = function(modelFit, newdata, submodels = NULL) { 
                    if(!is.matrix(newdata)) newdata <- as.matrix(newdata)
                    pred <- predict(modelFit, newdata, array.layout = 'rowmajor')
                    if(modelFit$problemType == "Regression") {
                      pred <- pred[1,]
                    } else {
                      pred <- modelFit$obsLevels[apply(pred, 2, which.max)]
                    }
                    pred
                  },
                  predictors = function(x, ...)  {
                    if(any(names(x) == "xNames")) x$xNames else NA
                  },
                  prob =  function(modelFit, newdata, submodels = NULL) {
                    if(!is.matrix(newdata)) newdata <- as.matrix(newdata)
                    pred <- t(predict(modelFit, newdata, array.layout = 'rowmajor'))
                    colnames(pred) <- modelFit$obsLevels
                    pred
                  },
                  tags = c("Neural Network"),
                  sort = function(x) x[order(x$nlayers, x$nnodes, x$nrounds, x$beta1, x$beta2, x$learningrate,x$dropout ),])
```

It works fine but the catch is that as you have discovered yourself [here](https://github.com/apache/incubator-mxnet/issues/1692) that short are very weak in terms of regression. That can put off people not willing to explore deeper networks. For the record I serialise the object right before the output; a side-effect is that to visualise the network with `graph.viz` one needs to `unserialize` it first, but it can be loaded/saved easily.

```R

train.ind = seq(1, 506, 3)
train.x = data.matrix(BostonHousing[train.ind, -14])
train.y = BostonHousing[train.ind, 14]
test.x = data.matrix(BostonHousing[-train.ind, -14])
test.y = BostonHousing[-train.ind, 14]

set.seed(88)
mxFit5 <- train(train.x , train.y, method =  mxnetAdam, preProcess = c("center", "scale"),
                tuneLength = 8, trControl = trainControl(method = "cv", verboseIter = TRUE))

set.seed(88)
mxFit7 <- train(train.x , train.y, method =  'glmnet', preProcess = c("center", "scale"),
                tuneLength = 8, trControl = trainControl(method = "cv", verboseIter = TRUE))
```

We can see that the drop in the RMSE/MAE metrics of `mxFit5` is very significant as we get to deeper networks.

**Comment by topepo** [comment]
You can. The issue right now is that I can't get the R package to build on OS X. The docs are out of date, disorganized, and don't work.

**Comment by hadjipantelis** [comment]
I will look into soon. The regression test are bit finicky to get right. 
I feel for you for the docs...

**Comment by hadjipantelis** [comment]
Got them. I have already one PR pending. I do not want to lump too much into it. When that one clears out I will make a new one for `mlpMxnetAdam`.

Sorry I have no experience on OSX. Are you at least able to get them running on Linux? (I can MXnet running on Debian and CentOS but not RHEL... )

**Comment by topepo** [comment]
I've got it running on linux now. 

Some thoughts: 

* I'm good with automatically having more than one layer but can you parameterize it in terms of `layer1`, `layer2`, `layer3` instead of `nlayers` and `nnodes`?
* Should the number of iterations be a tuning parameter? I generally let people set that for each run to some sufficiently high number. Adding it as a parameter ends up fitting the same model over and over for different numbers of rounds. 
* For the keras models, I'm parameterizing the activation functions (except for the final layer). Can you do the same here?
* I'll commit your code in a second along with some other mlp models. I've tried to standardize the parameter values and ranges so they might be different than what you sent above. I don't have too many strong opinions about these but I do want to try to keep them common. Please suggest alternatives to what I have. 
* IIRC your initializer (`mx.init.Xavier`) is not optimizer-specific so we can add that to the other models too.(?)
* Also, for the keras models, I have the optimizer use cross-entropy as the objective function for classification. That is probably a better option than accuracy. 
* We have to do the same serialization thing for keras models too. I've changed the code to only do it on the final model fit to save time. In the prediction/prob functions, we should check for serialization and unserialize the object when needed. 
* At some point, I'll write model-specific variable importance methods for these object classes (like I have for the others). 
* Try to call by namespace in the model code. In the devel version, we only load the namespace and not the whole package. 

Let me know what you think about these...

**Comment by hadjipantelis** [comment]
1. Do you mean forcing three layers to every case? (eg. like `mlpML` from `RSNNS`) I am somewhat against that because I think intuitively people would want to try networks of variable depth. I have seen first-hand that especially in regression shallower network are somewhat problematic. I think this might lead to people going for "wider" models - which is not the best idea for MLPs [(CV link)](https://stats.stackexchange.com/questions/222883).
2. Good point, I was thinking the same but opted to be more flexible in the expense of being more wasteful. Should I just make it so the user *has to* define it prior to running `mlpMXnetAdam`? The default is `10` and I have found it a place-holder value if anything. 
(Side-note: I looked into writing a `loop`; it is involved as we would have to use callback functions. I will need to study this further if needed.)
3. Good point, I was probably a bit heavy-handed.
4. I am using `adam` for optimisation, I think your code uses on `sgd`. Therefore I have changed the parameter values a bit for the random search, see [here](http://mxnet.io/api/python/optimization.html) for more details. I have changed my code a bit from the code above; when you get the PR please feel free to tell me the exact values you want (or edit them yourself).
5. Yes, it would be good for other models too.
6. Agreed, having said that (unfortunately) `mx.mlp` does not have cross-entropy available by default in R. A custom CC metric can be written. My only concern is that end-users might not notice it and there is a slow stream of comments "*my `mx.mlp` does not fit the same model*". Do we want to write one or stick with accuracy for compatibility purposes? 
7. Cool I will do the checks.
8. OK. (BTW, I don't know if you have checked by `pdp::partial` takes `caret::train` objects now and that's awesome!)
9. Yes, sorry; will do.

**Comment by hadjipantelis** [comment]
Minor additional question: Do you want me to change the name to `mlpMxnetAdam` or keep it `mxnetAdam`?

**Comment by topepo** [comment]
`mxnetAdam` would be good. 

Comments: 

> Do you mean forcing three layers to every case? 

No, but structurally allow for multiple layers as tuning parameters. In a few models I default the second and third layer to zero units. Having that parameterization might avoid the need for a custom model for someone. 

> Good point, I was thinking the same but opted to be more flexible in the expense of being more wasteful. Should I just make it so the user has to define it prior to running `mlpMXnetAdam`? 

Yes. the default is awful but I would leave it to the user to declare it and pass it in via the `...`

> when you get the PR please feel free to tell me the exact values you want (or edit them yourself).

I've put my suggestions in with the last commit. However, feel free to veto any. 

> `mx.mlp` does not have cross-entropy available by default in R

Huh. That's funny. I must have seem [this](http://mxnet.io/api/python/symbol.html#mxnet.symbol.softmax_cross_entropy), which may not work in this context (or be a pain to implement). That seems like a big oversight. 

Thanks

**Comment by hadjipantelis** [comment]
Hmm... I am still a bit on a cross-roads about the layers... I will check how easy it is to dynamically change the layers. Just having them as zero is a bit finicky regarding the call; I will look into it. Otherwise no problem, I will edit my next commit accordingly.

Regarding the cross-entropy: I trust only the code in the package under [metric.R](https://github.com/apache/incubator-mxnet/blob/master/R-package/R/metric.R)... (I could made a PR about it in `mxnet` but I think that would take more time.)

Thank you!

**Comment by topepo** [comment]
Let's leave it with accuracy then. We can adjust it later.

**Comment by hadjipantelis** [comment]
Agreed. As discussed: `num.round` is left to be defined through `...`, `activation` function is a tunable parameter now  and `Accuracy` is used (still). I did not find a non too-hacky why of defining `layer1`, `layer2`, etc. and still allow the user to change the number of layers so I left the `nlayers` parameters as it was. Regression test file is added. PR #722 Thank you for your time giving me feedback on this!

Minor notes: 

1. It could be desirable to remove `[mM]xnet` from the `parseModels.R` exclusions. I have removed from my local copy but I don't know if there are reasons to be excluded here. I was careful not to add them in the PR.
2.  For uniformity I left suggested hyperparameter ranges unchanged. I think the best solution would be for @thirdwing to give his educated suggestions. My thoughts: the range for `beta1/beta2` being lower than `0.50` is way too small for `adam`; similarly the `learningrate` of 2e-6 is extremely low for general applications.

**Comment by topepo** [comment]
1. Yes, I forgot about that.
 
2. Sounds good to me. I haven't used Adam so IK have no idea.

**Comment by hadjipantelis** [comment]
PR #722 amended for `layer1` to `layer3` use. 

I  am probably missing something here but if we use `layer1`, `layer2`and `layer3`, `layer4` to `layer9` are not tunable any more with the implementation in place for `mxnet` for example. The code in the `mxnet` implementation `param[grepl("layer[1-9]", names(param))]` is misleading, only layers 1 to 3 are passed, layers 4 and higher cannot be passed at all because they will not be valid parameters names. Any model with `layer4` parameter in the tune grid or in `...` will err. This brings us back to what I said about enforcing three layers to each case *at most* (sorry I should have clarified the at most). What if the user wants to work with five layers? (Which is one of the reasons to use like `mxnet` to begin with.)

Proposed solution: Maybe there is a `hidden_node` parameter instead of `layer1` to `layer3`? 
I can make the same change to `mxnet` too if you want. So for example if someone passes: `hidden_node = c(4,5,7)` it is a three layer network with 4, 5 and 7 nodes in each layer and if `hidden_node = rep(5,7)` user gets a seven layer network with 5 nodes in each layer. We can then simply check if the user has accidentally put `0` or `if( length(hidden_node) > 10)` to stop the computation.

**Comment by topepo** [comment]
`"layer[1-9]"` is a typo; it should be `"layer[1-3]"`. Sorry for the confusion. 

> What if the user wants to work with five layers? (Which is one of the reasons to use like `mxnet` to begin with.)

They would create a custom model. 

`hidden_node = c(4,5,7)` would be great except that the machinery for tuning parameters can't take a vector argument. That is basically what `num_units` ends up being in the `fit` module.

**Comment by hadjipantelis** [comment]
LOL! OK, I was on a different book chapter, let alone page, regarding the `layer` issue. No problem.
