### ISSUE TITLE
add attribute in model list binary/multi-class...(enhancement).

### ISSUE THREAD

**Issue by coforfe** [topepo/caret#329]
Hello,
I am using different classification models over a set that is multi-class (has 3 levels).
The issue is that besides some more or less familiar models (randomForest, Adabost, C5.0, gbm, XGB), when I try to use some others the first challenge I face is to know in advance if the algorithm supports **multi-class**. 

For instance, *"obliqueRF"* (oblique RandomForest) is just only for binary classification, and this happens with many others.

Would it be possible to include that info in the model list table?:
https://topepo.github.io/caret/modelList.html

Thanks,
Carlos.

**Comment by schelhorn** [comment]
I support this request. Additionally, it would be nice to see in the model list if a model accepts NAs in the predictors, if it directly accepts factors in the predictors (i.e. without explicit dummy expansion, as glinternet supports it, I believe), if it's a linear or a non-linear model, and if it supports the sub-model trick (since that will give you a free performance boost during model selection, so it's nice to know). I also suggest to add the ability to use class-weights during training to the list, but then that's not fully implemented in the caret resampling loop anyway, so there may not be a broad interest in it. 

Additionally, there already is information on implicit feature (or sometimes grouped feature) selection and feature importance cababilities in the docs, but this information is not accessible in a sortable tabular format. Having all this in sortable table would make dealing with the ever-increasing list of models (which is the great thing about caret, of course) much more convenient. 

Otherwise I fear that people may not be able to make use of all the shiny new models you are adding, since when in doubt they will prefer to stick with what they know and never learn about the new stuff. And that would be a shame, wouldn't it!

**Comment by topepo** [comment]
We could add model tags for "Multiclass" and "Accepts Missing Predictors". I'll write some code to figure out what models do what.

@schelhorn 

 > then that's not fully implemented in the caret resampling loop anyway, so there may not be a broad interest in it.

 * That is setup but requires the model-specific code to have weights implemented. If there are specific models that support weights but this isn't implemented in the model code, let me know. 
 * For the sub-model trick, you can check that via `unlist(lapply(mods, function(x) !is.null(x$loop)))`.

**Comment by schelhorn** [comment]
Yes, weights are supported but only as a global numeric vector, as far as I understood. Does _train_ do the right thing and match the appropriate weights to the samples actually present in each resampling iteration? The documentation wasn't very verbose in that respect. If yes, then this could be added to the docs on learning imbalanced classes, as it seems to be a suitable alternative approach to equalize the impact of less abundant classes, or am I mistaken?

**Comment by topepo** [comment]
Accepting missing data is hard to determine programatically. Does anyone have a list of models fitting these tags (beyond the ones that I tagged above)?

**Comment by coforfe** [comment]
Thanks.
`obliqueRF` is another one to include under the _accept 2 class outcomes_.
