### ISSUE TITLE
Using weights with method = 'earth'

### ISSUE THREAD

**Issue by apaust1** [topepo/caret#352]
I can reproduce a MARS model calling the function directly and using train. However when I pass a model that has a weight statement I cannot repeat the results. The results from the model with weights attached from train are identical to the results without a weight variable. 

When I inspect getModelInfo() I see the following for fit. 
$earth$fit
function (x, y, wts, param, lev, last, classProbs, ...) 
{
    theDots <- list(...)
    theDots$keepxy <- TRUE
    modelArgs <- c(list(x = x, y = y, degree = param$degree, 
        nprune = param$nprune), theDots)
    if (is.factor(y)) 
        modelArgs$glm <- list(family = binomial)
    tmp <- do.call("earth", modelArgs)
    tmp$call["nprune"] <- param$nprune
    tmp$call["degree"] <- param$degree
    tmp
}
It appears that wts has been left out of the call.

**Comment by topepo** [comment]
Previous versions of `earth` had the `weights` argument for consistency with earlier code/packages but weights were not implemented. For that reason, I didn't include them in the model code for `train`.

That seems to have changed. The version of `earth` that I have says
<pre>
 weights: Default is NULL, meaning no case weights.
          If specified, 'weights' must have length equal to 'nrow(x)'
          before applying 'subset'.
          The current implementation of weights is provisional and not
          fully tested.  Thus if weights are used a warning will be
          issued.  Supress just this warning with 'trace=-1' or
          'Force.weights=TRUE'.
</pre>

However, it looks like the current version (4.4.4  Jan 08, 2016) is solid since the NEWS file has 

     The weights argument has now been comprehensively tested and the 
     warning "support of weights is provisional" is no longer issued.

I will update my version of `earth` and the `fit` module.

**Comment by topepo** [comment]
Thie also affects `bagEarth`, `bagEarthGCV`, `bagFDA`, `bagFDAGCV`, `fda`, and `gcvEarth` so it may take some time.
