### ISSUE TITLE
time series models in train

### ISSUE THREAD

**Issue by topepo** [topepo/caret#359]
Quite a few people have asked to include these models in the package so that they can tune models with `train`. 

Right now, the only time-series related features are [rolling forecast origin resampling](http://topepo.github.io/caret/splitting.html#time) but this is general purpose. 

Here is what I see as the issues for including time series models:

 1. I assume that most data sets will be class `ts` (please invalidate this if it is not the case). Right now, you could use `train` by having a data frame with a column for the time variable and another for the outcome. I would think that maintaining the original class would be important instead of reconstructing it inside `train` especially since some of the original data will be used as the holdout. We can make `train.ts` as a new class but that might take some work. 

 2. `train` wouldn't do a great job on forecasting. For example, the `predict` function only returns a single scalar result per data point. It would not be able to produce forecast errors unless you predict from the original model object (which can be dicey)

Max

**Comment by mlu68** [comment]
I am not using specific time series models, but rather usual machine learning models for time series.
My concern is more for large dataset, because cross-validation with trainControl / method = "timeslice" becomes very slow (because of the one by one increment).
That is why I often the alternative suggested by Hyndman: "another vari­a­tion which is use­ful for large data sets is to use a form of k-​​fold cross-​​validation where the train­ing sets incre­ment by sev­eral val­ues at a time. For exam­ple, instead of incre­ment­ing by one obser­va­tion in each iter­a­tion, we could shift the train­ing set for­ward by 12 observations." (http://robjhyndman.com/hyndsight/tscvexample/)
To my mind, it could be interesting to add this alternative in the caret cross-validation for time series features (not a big deal, as you can see).

**Comment by zachmayer** [comment]
You can always pass your own indexes to `trainControl(index=...)` and `trainControl(indexOut=...)`.  See also the `createTimeSlices` function, e.g.:

```{R}
#increment by 1
> createTimeSlices(1:10, 7, 1)
$train
$train$Training1
[1] 1 2 3 4 5 6 7

$train$Training2
[1] 2 3 4 5 6 7 8

$train$Training3
[1] 3 4 5 6 7 8 9


$test
$test$Testing1
[1] 8

$test$Testing2
[1] 9

$test$Testing3
[1] 10
```
or
```{R}
#increment by 3
> createTimeSlices(1:10, 7, 3)
$train
$train$Training1
[1] 1 2 3 4 5 6 7


$test
$test$Testing1
[1]  8  9 10
```

**Comment by zachmayer** [comment]
@topepo I agree with your point that supporting the initial `ts` class would be ideal.  We could potentially write wrapper functions to convert `ts` classes to `data.frames`, with optional additional columns, e.g. seasonal dummy variables using `forecast::seasonaldummy()`.

Using caret for forecasting could be solved by using `forecast::seasonaldummyf()` to forecast the co-variables in a data.frame, which is then passed to `caret::predict` and the original model.

Also not that I've tried to tackle some of these issues in my [cv.ts](https://github.com/zachmayer/cv.ts) package, where [I created a function that wraps `caret` models inside of `forecast` models](https://github.com/zachmayer/cv.ts/blob/master/R/forecast_helper_funs.R#L109-L113).  Note the `newxreg` argument, which is similar to the `newxreg` argument in [`predict.Arima`](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/predict.arima.html).

**Comment by mlu68** [comment]
Thank you Zach.
I wasn't aware of this use of createTimeSlices function. Sorry.
Let me test this as soon as possible.
Best regards

2016-01-27 22:57 GMT+01:00 Zach Mayer <notifications@github.com>:

**Comment by topepo** [comment]
> I am not using specific time series models, but rather usual machine learning models for time series.
My concern is more for large dataset, because cross-validation with trainControl / method = "timeslice" becomes very slow (because of the one by one increment).
> That is why I often the alternative suggested by Hyndman: "another vari­a­tion which is use­ful for large data sets is to use a form of k-​​fold cross-​​validation where the train­ing sets incre­ment by sev­eral val­ues at a time. For exam­ple, instead of incre­ment­ing by one obser­va­tion in each iter­a­tion, we could shift the train­ing set for­ward by 12 observations." (http://robjhyndman.com/hyndsight/tscvexample/)

You can do this with `createTimeSlices`:

```r
> createTimeSlices(1:20, initialWindow = 2, skip = 4)
$train
$train$Training01
[1] 1 2

$train$Training06
[1] 6 7

$train$Training11
[1] 11 12

$train$Training16
[1] 16 17


$test
$test$Testing01
[1] 3

$test$Testing06
[1] 8

$test$Testing11
[1] 13

$test$Testing16
[1] 18
```

It looks like `skip` isn't available in `trainControl` so, for now, you can create them yourself and pass the results in using `index` and `indexOut`.

**Comment by topepo** [comment]
@zachmayer I had not seen that package. I'll check it out; it well be the best approach to solving this if it works within `forecast`

**Comment by sfeuerriegel** [comment]
The `caret` package is doing a great job in making predictions (thanks to all authors!). Our research team is working on several instances where we make time-series forecasts and encountered several challenges. I'll summarize them briefly below. 

We have also experimenting with a few internal scripts that help us doing our research. For instance, I will refer below to a case where we make forecasts of hourly electricity prices and we make these predictions always for the subsequent day. 

1. We usually avoid working with `ts`, as one then must explicitly handle days with day-light saving time (they have 23 / 25 hourly slots). Hence, we usually work with a simple data frame as we can swipe through it in steps of 24 hours. 
2. We make predictions day ahead (so we essentially loop over `predict()` for 24 hours)
3. We backtest our algorithm by iteratively refitting the models. We take the historic data, calibrate our models, make a predictions for -- let's say -- Jan 1. We then evaluate the forecast. Afterwards, we take all historic data (incl. Jan 1) and refit our models to make the prediction for Jan 2, and so on ... Essentially, we include another *outer loop* to iterate over the data. I have made the experience that controling the frequency of re-fitting is critical as it is likely to push the runtime. 
4. We usually compare machine learning and naive time series models (for instance, autoregressive processes with exogenous variables). These help us to have a nicer interface when we want to include lagged values. Our aim was to come-up with consistent interface, as we wanted to use caret's `train()` for all routines. They are on GitHub (https://github.com/sfeuerriegel/caret.ts), however, the interface etc. is not as good as it could be. 
5. Lastly, plotting in a fashion like the `forecast` package would be nice; but, I have not yet needed it for research. 

Another show-case where we are using the above code snippets is the following example: we generated a term-document matrix from news in order to predict macroeconomic indicators.. So we compare ML with the term-document matrix to naive time series models.

**Comment by topepo** [comment]
> We usually compare machine learning and naive time series models (for instance, autoregressive processes with exogenous variables). These help us to have a nicer interface when we want to include lagged values. Our aim was to come-up with consistent interface, as we wanted to use caret's train() for all routines. They are on GitHub (https://github.com/sfeuerriegel/caret.ts), however, the interface etc. is not as good as it could be.

So what kinds of interface would you like? Can you dummy-up some code to show how you _would_ like it to look? 

> We backtest our algorithm by iteratively refitting the models. We take the historic data, calibrate our models, make a predictions for -- let's say -- Jan 1. We then evaluate the forecast. Afterwards, we take all historic data (incl. Jan 1) and refit our models to make the prediction for Jan 2, and so on ... Essentially, we include another outer loop to iterate over the data. 

Do you do this manually with `for` loops over data frames? It sounds a lot like the rolling forecast origin forecasting resampling scheme.

**Comment by randomgambit** [comment]
@topepo hello everyone and thanks again for this amazing package! 

I am also interested in using caret with time series, but by looking at the documentation, it seems to me the time slices do not take into account the time dimension (not `ts` class needed - which is good)

So if I understand well you can only specify how many observations you have in each slice vs. how many days / months/ time units. Am I correct? 

Thanks!

**Comment by topepo** [comment]
> time slices do not take into account the time dimension

No, they don't. 

> So if I understand well you can only specify how many observations you have in each slice vs. how many days / months/ time units. Am I correct?

You are correct. If you had data over a year period and wanted the slices to be in weeks, you would need to determine the right resampling parameters that correspond to the granularity of your data (e.g. are your data in days, weeks, etc).

**Comment by randomgambit** [comment]
hello there! any updates on this? can we run ARIMA models with Caret?
Thanks and keep up with the good work!!!

**Comment by topepo** [comment]
It looks like `caret.ts` has it covered but if you want a native implementation of those models in `caret`, someone who knows a bit about time series models (i.e. not me) would have to add these models. I can help that process if there is a volunteer.

**Comment by randomgambit** [comment]
thanks @topepo ... yeah the problem is that `caret.ts` is maintained by just one guy and not very active... a bit hesitant to use it. Well at the end of the day one can still use caret and run an ARIMA manually with `lm` and specifying the lags manually say `lm( Y ~ lag_Y lag2_Y lag3_Y X)`

**Comment by topepo** [comment]
>`lm` and specifying the lags manually say `m( Y ~ lag_Y lag2_Y lag3_Y X)`

Once I get around to adding the lag steps, you could do that with [recipes](https://topepo.github.io/recipes/)

**Comment by randomgambit** [comment]
hi @topepo how are you? any update on that?

**Comment by cjmalloy** [comment]
Would it be possible to pull in the caret.ts project into this one? It seems it might be abandoned, but was working at one time.
