### ISSUE TITLE
Allow specification of a "missing" value in xgbTree

### ISSUE THREAD

**Issue by tycragg** [topepo/caret#381]
Hi Max,

Would it be at all possible for you to allow specification of a "missing" value within the "train" call for xgbTree? In the xgboost package, this "missing" value can be optionally specified when creating the xgb.DMatrix as follows:

xgb.DMatrix(as.matrix(x), label = y, missing=-999)

It is also specified when predicting on the model:

predict(modelFit, newdata, missing=-999)

Thanks as always for your hard work.

**Comment by topepo** [comment]
If these were parameters to `xgb.train`, you could pass them through with `train`. However, specially since you need to change the `predict` syntax, your best bet is to make a [custom model](http://topepo.github.io/caret/custom_models.html). For example:

```r
> code <- getModelInfo("xgbTree")[[1]]
> names(code)
 [1] "label"      "library"    "type"       "parameters" "grid"       "loop"       "fit"       
 [8] "predict"    "prob"       "predictors" "varImp"     "levels"     "tags"       "sort"    
```

and modify the elements that you need to change.

**Comment by jmrichardson** [comment]
Hi, I am trying to pass "missing = NaN" via train and still get the following error:
There are NAN in the matrix, however, you did not set missing=NAN 

Here is the code
```
xgbTrain = train(
  x = data.matrix(train),
  y = trainLabel,
  tuneGrid = xgbGrid,
  trControl = xgbControl,
  method = 'xgbTree',
  missing = NaN
)

```
