### ISSUE TITLE
Feature request: rBayesian

### ISSUE THREAD

**Issue by dashaub** [topepo/caret#436]
Your recent post on using a Bayesian search for hyperparameters was excellent. In fact, about a quarter into the post I got the idea of using a random search initially and then using those results to initialize the Bayesian search, so it was great to see you took the same approach. Is there any chance of integrating the "rBayesian" package so there is an option `search = "bayesian"` in `trainControl()`?

**Comment by topepo** [comment]
I'd like to be able to do that but it is fairly complicated:

 * although we have some data for each model on the tuning parameters, setting the ranges required for the BO, isn't in the model code right now. In some cases, it would be data dependent and would require code rather than fixed numbers to figure out
 * we wouldn't be able to do it for every model unless we get creative. For example, for naive Bayes, we can optimize on the distribution type (Gaussian or kernel), the kernel parameter, and the Laplace correction value. The distribution is discrete and wouldn't fit in to the GP model well unless you made it binary and then truncated the value that the GP produced.  Also, one of the parameters depends on the distribution type, etc. 

The first step would be to figure out how to deal with the ranges for the parameters and encode these into the model components. From there, we can deal with the underlying logic of how it works. 

I'll list this as an "enhancement" option and will keep it open until I can either get started on doing it or punt.

**Comment by dashaub** [comment]
- Can we use some modification of the ranges used for each model when `search = "random"` for this? As I understand from the documentation, those ranges are supposed to capture a large range of reasonable tuning values, but as we saw BO will likely explore extreme values that we wouldn't consider. If the random search ranges aren't used, could we simply impose constraints for the considered parameters as appropriate to each model (e.g. must be nonnegative, must be in (0, 1), must be whole number, etc)?
- That is a serious issue and some creativity would be required. I like your idea of focusing on the ranges first and rolling our a solution for the non-numeric and interaction parameters later.

**Comment by topepo** [comment]
> Can we use some modification of the ranges used for each model when search = "random" for this? 

That's along the lines of what we would do. The code modules could be changed to add a new component (called something like `ranges`) and have the `grid` function reference that when doing random or gird search. It would be good to avoid an extra argument to the `grid` component so it would be good to figure out how to make the code modules self referential (i.e. call the `ranges` component within the `grid` component).  

> That is a serious issue and some creativity would be required. I like your idea of focusing on the ranges first and rolling our a solution for the non-numeric and interaction parameters later.

I would do it in steps. First, make the change and validate that you get the same answers for grid and random search (using the [regression tests](https://github.com/topepo/caret/tree/master/RegressionTests) that we have). After that, start a workflow for BO.

**Comment by dashaub** [comment]
ok, I'll try to take a more detailed look at the code this weekend and think about implementation.

**Comment by dashaub** [comment]
@topepo What about when a parallel backend has been registered and is used for the model search? Supporting that seems difficult with the self referential components.

**Comment by topepo** [comment]
That shouldn't be an issue. We would do it a few different ways but probably just create a wrapper around the model creation/prediction code (or maybe even `train`) using `foreach`. That is how the workflows currently do it.

**Comment by BU-1** [comment]
This would be a really great feature! Are there any methods currently available for using Bayesian optimization with `caret`?

**Comment by topepo** [comment]
This is a good idea and is implemented in `tidymodels`. 

Unfortunately, `caret` is at the lifecycle point of having a fairly complete interface, so this isn't a good fit.  

The development work is focused on squashing bugs and any changed required by the underlying model packages.
