### ISSUE TITLE
Variable train() behaviour with Linux parallel backend using MKL optimization

### ISSUE THREAD

**Issue by adam-erickson** [topepo/caret#443]
Some of the models with `train` show odd behaviour when using Microsoft R Open (MKL optimized R) and `DoMC` on Linux. Some models over-consume CPU resources (e.g., Boruta), while others crash if more than one fork is specified (e.g., svmRadial). In general, functions called by `train` need to be harmonized in terms of their parallel backend frameworks. I'm sure that is no easy task.

**Comment by topepo** [comment]
`train` uses `foreach` in a straight-forward way. Unless you can provide a reproducible example where the issue is localized to `caret`, I would contact the `foreach` package maintainer first.

**Comment by dashaub** [comment]
This is really a MRO and MKL issue: caret only uses parallelization for the embarassingly parallel task of fitting multiple models with separate hyperparameters simultaneously. Obviously if your R session is trying to utilize multiple cores for a matrix inversion, multiplication, etc, there will be resource competition and performance degradation when also using parallelization with caret. I imagine the problem here arises for models that implement base R operations that MKL is parallelizing, while models with C/C++/Fortran/Java code would run fine.
