### ISSUE TITLE
reverse engineering random forest predictions

### ISSUE THREAD

**Issue by einats** [topepo/caret#455]
A very general question:

I have trained a classification random forest model, and am very happy with the results.
Next I use the model to predict outcomes on new data. 
I'm being asked, why specific data gets a specific predicted outcome. Since random forest is a black box, I don't see how to answer this question
I know which predictors are important in the model, but not which were used for predicting a specific instance.
Is it possible to extract the predictors most important for a specific outcome (rather than the whole model)?

thanks

**Comment by zachmayer** [comment]
Iterate through all the columns in your prediction row, and replace the value in that row with the median of that column.  Re-predict, and see how much your prediction changes. (You can use the mode for categorical columns and median for numeric columns).

Whichever column resulted in the biggest change in the predicted value when replaced with the median is your most important predictor for that specific outcome.

This is obviously very time consuming, because you need to make one extra prediction per column in your dataset.

**Comment by gangstR** [comment]
As @zachmayer stated, the process can be rather time consuming.  Here's a link to an article from a couple of months ago that addresses variable importance at the individual prediction level (includes R code examples and a link to a YouTube video):  http://amunategui.github.io/actionable-instights/index.html.  

On a somewhat related note, some friends of mine from Google put together a package specifically to peek into the RF blackbox with some visualizations.  Their package was called glassbox.  Ben and Max spoke about it at JSM two years ago.  While their package is geared to help you understand interactions rather than the nature of individual predictions, it does attempt to dispel the "blackbox" perception of RF.  Their code is on GitHub here: https://github.com/google/glassbox.

I hope you find these links helpful.

**Comment by topepo** [comment]
@gangstR (great name) Thanks for the link and info. I had forgotten about that. 

@einats I hope the info from @gangstR helps and, since this isn't really a `caret` related question, I'm going to close the issue.

**Comment by einats** [comment]
thank you @gangstR I'll go digging into the information you sent.
