### ISSUE TITLE
Cross-validated rfe: how is the final "best" feature set selected?

### ISSUE THREAD

**Issue by MassimilianoGrassiDataScience** [topepo/caret#487]
It is expected that the best features selected by rfe in each CV fold may differ, as also stated in the caret page

> Another complication to using resampling is that multiple lists of the
> “best” predictors are generated at each iteration. At first this may
> seem like a disadvantage, but it does provide a more probabilistic
> assessment of predictor importance than a ranking based on a single
> fixed data set. At the end of the algorithm, a consensus ranking can
> be used to determine the best predictors to retain.

However it is not clear to me how the final "best" set of predictors is chosen in *rfe*, considering this expected heterogeneity among folds. I cannot find the procedure of the "consensus ranking" mentioned above.

Thank you!

**Comment by topepo** [comment]
That isn't very clear :-/

`rfe` conducts a backwards selection within each resample and tracks which variables were selected in each subset and how the holdout performance changed. Once resampling is complete, the holdouts are used to determine the best _subset size_. Once it knows that, it does the backwards elimination proceeds in exactly the same way (except that the whole data set is used), and uses the subset size that was previously determined. 

I think that your question is more "how are the predictors ranked?". The answer to that depends on the model. For example, random forest has its own importance score but an SVM model does not so a model-free independent score is used. See this [page for some details](http://topepo.github.io/caret/variable-importance.html).

Irregardless, once the predictors are ranked, the final model is created by selecting the top _X_ predictors based on the results of the resampling process and the rankings on the entire data set. 

The  "consensus ranking" bit is an alternative to using a single ranking generated by the entire data set in the final RFE. Since we know which predictors were selected at each stage during resampling, we can see what the variation was in these rankings across resamples. 

Here is an example:
```r
set.seed(12507)
dat <- twoClassSim(100)

set.seed(4714)
mod <- rfe(x = dat[, -ncol(dat)], y = dat$Class,
           sizes = c(1, 5, 10),
           rfeControl = rfeControl(method = "cv", functions = treebagFuncs))

## This approximates the full model used in the process of getting `mod` above
set.seed(69136)
full_model <- bagging(Class ~ ., data = dat)
final_imp <- varImp(full_model)
## larger is better here
final_imp$rank <- rank(final_imp$Overall)
final_imp <- final_imp[order(-final_imp$rank),]
```
```r
> final_imp
             Overall rank
Linear03   24.881739   15
TwoFactor1 22.996381   14
TwoFactor2 21.037424   13
Linear07   13.936479   12
Linear05   13.233400   11
Linear04   12.991575   10
Linear01   10.368295    9
Linear02    9.323789    8
Linear08    9.121460    7
Linear06    8.907849    6
Linear09    6.987751    5
Nonlinear2  6.783710    4
Linear10    5.666849    3
Nonlinear3  3.742956    2
Nonlinear1  3.705173    1
```
Here is what the resampling process generated: 
```r
all_imps <- mod$variables
all_imps <- all_imps[order(-all_imps$Variables, all_imps$Resample, all_imps$var),]
```
```r
> head(all_imps)
     Overall      var Variables Resample
7   9.115147 Linear01        15   Fold01
10  6.601828 Linear02        15   Fold01
2  22.452338 Linear03        15   Fold01
6   9.306426 Linear04        15   Fold01
5  13.279637 Linear05        15   Fold01
9   6.778237 Linear06        15   Fold01
> tail(all_imps)
     Overall        var Variables Resample
155 20.99155   Linear03         1   Fold05
186 21.65159   Linear03         1   Fold06
217 22.30088 TwoFactor1         1   Fold07
248 22.94867   Linear03         1   Fold08
279 22.55221   Linear03         1   Fold09
310 21.50473 TwoFactor1         1   Fold10
```
At this point we can take the average rankings or calculate the percentage of times that each predictor made it to a specific stage. For example: 
```r
library(plyr)

averaged <- ddply(subset(all_imps, Variables == 15),
                  .(var), 
                  function(x) c(Mean = mean(x$Overall),
                                sd = sd(x$Overall)))

averaged$resamp_rank <- rank(averaged$Mean)
final_imp$var <- rownames(final_imp)
```
```r
> merge(averaged, final_imp)
          var      Mean        sd resamp_rank   Overall rank
1    Linear01  8.602532 2.0316237           9 10.368295    9
2    Linear02  7.842667 1.2347468           8  9.323789    8
3    Linear03 20.848299 1.8569648          14 24.881739   15
4    Linear04  9.802899 1.6755479          10 12.991575   10
5    Linear05 15.272970 2.1225616          12 13.233400   11
6    Linear06  7.318263 1.3138241           7  8.907849    6
7    Linear07 13.161584 2.1084067          11 13.936479   12
8    Linear08  7.052826 1.4007210           6  9.121460    7
9    Linear09  4.785395 0.9354787           3  6.987751    5
10   Linear10  4.916626 0.8471797           4  5.666849    3
11 Nonlinear1  4.712164 1.0280549           2  3.705173    1
12 Nonlinear2  6.952920 1.8439250           5  6.783710    4
13 Nonlinear3  4.700670 0.7644578           1  3.742956    2
14 TwoFactor1 21.578673 1.0432276          15 22.996381   14
15 TwoFactor2 18.518142 1.6023877          13 21.037424   13
```

If we wanted, we could use the resampled rankings instead (although there is no top-level "switch" to do this in `rfe`). The rankings could be different but in this case they are fairly consistent. If you thought that 6 predictors was best, then: 
```r
> sort(final_imp$var[final_imp$rank <= 5])
[1] "Linear09"   "Linear10"   "Nonlinear1" "Nonlinear2" "Nonlinear3"
> sort(averaged$var[averaged$resamp_rank <= 5])
[1] "Linear09"   "Linear10"   "Nonlinear1" "Nonlinear2" "Nonlinear3"
```

**Comment by MassimilianoGrassiDataScience** [comment]
Thank you Max! Now it's much more clear!

**Comment by MassimilianoGrassiDataScience** [comment]
I actually have two more questions:

- considering the first phase (subset size identification in each resample), is the ranking calculated only at the beginning (i.e. using the whole feature set) or instead is it recalculated after each variable drop? There may be a swap in the ranking order of some variables after other have been removed.
- considering instead the last phase, after that the whole sample ranking has been calculated and the subset size defined, is the same resampling scheme applied before used also to calculate the performance of the final model?

Thank you!

**Comment by topepo** [comment]
For the ranking, you can do it either way. There is an option in `rfeControl` that defaults to create the rankings once at the very beginning using the full model. The literature (and my experience) shows a small improvement by doing a single ranking at the start. 

There is no resampling scheme in the last phase since it uses the entire training set.

**Comment by MassimilianoGrassiDataScience** [comment]
Dear Max,
sorry, one final question. 

I see that with `caretFuncs`it is possible to optimize also for the hyperparameters of the model. But browsing in the results obtained with `rfe` I can find specifics of the results for the various hyperparameter configurations only in `_model-name_$fit`, not for example in `_model-name_$results`. How does it work? Is it possibile to calculate the optimal number of features independently for each hyperparameter configuration? Otherwise, which single hyperparameter configuration is used in the first phase?

Thanks again!

**Comment by topepo** [comment]
No problem. The hyperparameter optimization occurs at each stage of the process, i.e. within each resample and subset combination. On the final iteration, it is also done on the whole data set for the final subset (size) that has been selected. Basically, it is inside the "module" of the model fitting process and that module is called for every data set and subset that is evaluated.

**Comment by MassimilianoGrassiDataScience** [comment]
Thanks Max!

I found results regarding the hyperparameter optimization in `model-name$fit. But I cannot find evidence of this process in both `model-name$results` and `model-name$resamples`, where no hyperparameter values are specified and only one single results for each resample/amount_of_variables combination is available. Are `model-name$results` and `model-name$resamples` only those of the model with the best hyperparameters?

**Comment by topepo** [comment]
>  Are model-name$results and model-name$resamples only those of the model with the best hyperparameters?

Yes, that is the case.

**Comment by MassimilianoGrassiDataScience** [comment]
Thanks a lot!

**Comment by kransom14** [comment]
Suppose we wanted to keep the top 6 variables and used `mod$optVariables[1:6]`, are the variables listed in mod$optVariables based on the consensus/average ranking above, or based on the final ranking with the model run with all data and the optimal number of variables?
