### ISSUE TITLE
Feature Selection and Parameter Tuning

### ISSUE THREAD

**Issue by jroberayalas** [topepo/caret#503]
I've been using the caret package to perform either feature selection or hyperparameter tuning, but I was wondering if there's a way to perform both within the same pipeline for models that do not have a built-in feature selection mechanism.

**Comment by topepo** [comment]
For `rfe` you can be using `caretFuncs` as your functions. That will re-tune every time you evaluate a new subset. `sbf`, `gafs`, and `safs` have similar function sets. 

Does that solve the issue?

**Comment by jroberayalas** [comment]
Yes, it does! Sorry, I forgot to reply. Thanks a lot for your help.

**Comment by wvictor14** [comment]
Hi @topepo could you clarify if the parameter tuning is done 'inner' to the feature selection? 

As in, within the cross validation folds produced by `sbfControl(method='cv')`, inner folds are created for parameter tuning as specified by `trainControl(method='cv')`?

What if I want to cross validate both feature selection and parameter tuning simultaneously? for example:


1. for each parameter set:
    i. hold out samples
    ii. select features on remaining samples, and then fit model with these features
    iii. predict on held-out samples
2. return  best set of parameters/feature set and fit to entire dataset

Can I achieve this with sbf / train functions?

**Comment by topepo** [comment]
I'll answer this here but please try to submit a new issue instead of appending to a closed one. It's easy to lose track of these questions without a new issue. 

Within each resample, `sbfIter` is executed. Here is a "enhanced commented version":
```r
sbfIter <-
  function (x, y, testX, testY, sbfControl = sbfControl(), ...) {
    # Compute the scores for each predictor in `x`
    if (sbfControl$multivariate) {
      scores <- sbfControl$functions$score(x, y)
    }
    else {
      scores <- apply(x, 2, sbfControl$functions$score, y = y)
    }
    # Use a filter rule to cull them
    retained <- sbfControl$functions$filter(scores, x, y)
    testX <- testX[, which(retained), drop = FALSE]
    
    # Fit/tune the model using only the variables that survived the
    # feature selection filter. If you pass `trainControl` using
    # the ... it will do more (=inner) resampling here using the 
    # current (outer) resamples:
    fitObject <- sbfControl$functions$fit(
      x = x[, which(retained), drop = FALSE], 
      y = y, 
      ...
    )
    
    # Predictions on the external holdouts
    modelPred <- sbfControl$functions$pred(fitObject, testX)
    if (is.data.frame(modelPred) | is.matrix(modelPred)) {
      if (is.matrix(modelPred))
        modelPred <- as.data.frame(modelPred)
      modelPred$obs <- testY
    }
    else
      modelPred <- data.frame(pred = modelPred, obs = testY)
    list(variables = names(retained)[which(retained)], pred = modelPred)
  }
```
One resampling is done, this exact process is repeated one last time on the entire training set. `sbf` collects the predictors that were selected in the resamples, but doesn't explicitly use them for the final model fit.

**Comment by wvictor14** [comment]
OK, I'll submit a new issue next time instead of responding to a closed one. 

Thank you for the explanation, it was very clear. I have a follow-up question that might be a naive one:

Why do we do these two processes (feature selection and parameter tuning) in this particular order? Feature selection would likely affect which parameters are best, and which parameters are selected may impact which set of features is optimal. In this package it seems like the ordering is fixed, so it seems like there is a reason behind it.
