### ISSUE TITLE
Error in training rlm with interaction terms

### ISSUE THREAD

**Issue by SergioEanX** [topepo/caret#526]
If I try to train a robust linear regression model with  interactions terms I get an error as:

> Error in train.default(x, y, weights = w, ...) : Stopping
> In addition: Warning message:
> In nominalTrainWorkflow(x = x, y = y, wts = weights, info = trainInfo,  :
>   There were missing values in resampled performance measures.

### Minimal, reproducible example:
For example : 

```{R}
library(caret); library(MASS)
 mod <- train(
      mpg ~ wt*cyl+ hp,
      data = mtcars,
      method = "rlm",
      metric = "RMSE",
      preProc= c("center","scale","BoxCox"),
      trControl =  trainControl(method="cv", number = 5),
      na.action=na.omit
    )

Something is wrong; all the RMSE metric values are missing:
      RMSE        Rsquared  
 Min.   : NA   Min.   : NA  
 1st Qu.: NA   1st Qu.: NA  
 Median : NA   Median : NA  
 Mean   :NaN   Mean   :NaN  
 3rd Qu.: NA   3rd Qu.: NA  
 Max.   : NA   Max.   : NA  
 NA's   :6     NA's   :6  

```
On the contrary, removing the interaction term:

```{R}
mod <- train(
+      mpg ~ wt+cyl+ hp,
+      data = mtcars,
+      method = "rlm",
+      metric = "RMSE",
+      preProc= c("center","scale","BoxCox"),
+      trControl =  trainControl(method="cv", number = 5),
+      na.action=na.omit
+    )
> mod
Robust Linear Model 

32 samples
 3 predictor

Pre-processing: centered (3), scaled (3), Box-Cox transformation (3) 
Resampling: Cross-Validated (5 fold) 
Summary of sample sizes: 24, 24, 26, 28, 26 
Resampling results across tuning parameters:

  intercept  psi           RMSE       Rsquared 
  FALSE      psi.huber     20.394033  0.9134203
  FALSE      psi.hampel    20.394033  0.9134203
  FALSE      psi.bisquare  20.393673  0.9132495
   TRUE      psi.huber      2.435733  0.9091399
   TRUE      psi.hampel     2.467122  0.9128827
   TRUE      psi.bisquare   2.493137  0.9062256

RMSE was used to select the optimal model using  the smallest value.
The final values used for the model were intercept = TRUE and psi = psi.huber. 
```

### Session Info:
```{R}
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=Italian_Italy.1252  LC_CTYPE=Italian_Italy.1252   
[3] LC_MONETARY=Italian_Italy.1252 LC_NUMERIC=C                  
[5] LC_TIME=Italian_Italy.1252    

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

other attached packages:
[1] MASS_7.3-45     caret_6.0-73    ggplot2_2.2.0   lattice_0.20-34

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.7        magrittr_1.5       splines_3.3.2      munsell_0.4.3     
 [5] colorspace_1.3-0   foreach_1.4.3      minqa_1.2.4        stringr_1.1.0     
 [9] car_2.1-3          plyr_1.8.4         tools_3.3.2        parallel_3.3.2    
[13] nnet_7.3-12        pbkrtest_0.4-6     grid_3.3.2         gtable_0.2.0      
[17] nlme_3.1-128       mgcv_1.8-16        quantreg_5.29      e1071_1.6-7       
[21] class_7.3-14       MatrixModels_0.4-1 iterators_1.0.8    lme4_1.1-12       
[25] lazyeval_0.2.0     assertthat_0.1     tibble_1.2         Matrix_1.2-7.1    
[29] nloptr_1.0.4       reshape2_1.4.2     ModelMetrics_1.1.0 codetools_0.2-15  
[33] stringi_1.1.2      compiler_3.3.2     scales_0.4.1       stats4_3.3.2      
[37] SparseM_1.74 

``

**Comment by hadjipantelis** [comment]
What you experience is the function `rlm` being finicky with names including colons (`:`). `caret`'s `createModel` will attempt to create a model matrix using the variable names:  `"wt"` `"cyl"`    `"hp"`     `"wt:cyl"`; these names are assigned automatically. When that model matrix / data.frame including the colname `wt:cyl` is passed to `rlm`, `rlm` will fail.

You can see it as follows: we create a matrix `MM` holding the explanatory variables information. Because of the name used you get exactly the same error as in your example:

```R
MM = model.matrix(lm( mpg ~ -1 + wt * cyl+ hp, data= mtcars)) 
colnames(MM)
# [1] "wt" "cyl" "hp" "wt:cyl"
mod <- train( y = mtcars$mpg, x = MM, method = "rlm", metric = "RMSE", 
              trControl =  trainControl(method="cv", number = 5)) 
              # Same error as the one you experience
```
if you changed the variable name the error would not occur:

```R
colnames(MM)[4] <- 'wtCOLONcyl'
colnames(MM)
# [1] "wt" "cyl" "hp" "wtSCOLONcyl"
mod <- train( y = mtcars$mpg, x = MM, method = "rlm", metric = "RMSE", 
              trControl =  trainControl(method="cv", number = 5)) 
              # Function runs successfully - aside unrelated convergence issues at times
```

Just to ensure that this is a `rlm` issue, I reproduce this outside `caret` too:

``` R
MM = model.matrix(lm( mpg ~ -1 + wt * cyl+ hp, data= mtcars)) 
data1 = as.data.frame(MM)
data1$mpg <- mtcars$mpg

qRLM = rlm(mpg ~ ., data = data1) # This errs

colnames(data1)[4] <- "wtCOLONcyl"
qRLM = rlm(mpg ~ ., data = data1) # This works
```

*Immediate work-around*: 
  Explicitly define the arguments `x` and `y` taking care not to use `:` in the column names.

I think that this is not a `caret` bug but rather a `rlm` bug.

**Comment by SergioEanX** [comment]
Thanks for your illuminating reply !

**Comment by topepo** [comment]
Thanks for answering!

**Comment by zippeurfou** [comment]
@topepo One error that is still existing with the model is the intercept that do not get removed.
```
> MM = model.matrix(lm( mpg ~ -1 + wt * cyl+ hp, data= mtcars))
> colnames(MM)[4] <- 'wtCOLONcyl'
> mod <- train( y = mtcars$mpg, x = MM, method = "rlm", metric = "RMSE",
+               trControl =  trainControl(method="cv", number = 5))
> summary(mod)

Call: rlm(formula = .outcome ~ ., data = dat, psi = psi)
Residuals:
    Min      1Q  Median      3Q     Max
-3.5927 -1.1627 -0.2367  1.2645  5.3572

Coefficients:
            Value   Std. Error t value
(Intercept) 51.6155  5.7235     9.0182
wt          -8.1157  2.1800    -3.7227
cyl         -3.0043  0.9645    -3.1147
hp          -0.0190  0.0105    -1.8026
wtCOLONcyl   0.7446  0.3080     2.4176

Residual standard error: 1.874 on 27 degrees of freedom
```

**Comment by topepo** [comment]
That is a tuning parameter for this model. Seethe entry in `?models`.


On June 14, 2017 at 4:07:51 PM, Marc Ferradou (notifications@github.com)
wrote:

@topepo <https://github.com/topepo> One error that is still existing with
the model is the intercept that do not get removed.

> MM = model.matrix(lm( mpg ~ -1 + wt * cyl+ hp, data= mtcars))
> colnames(MM)[4] <- 'wtCOLONcyl'
> mod <- train( y = mtcars$mpg, x = MM, method = "rlm", metric = "RMSE",
+               trControl =  trainControl(method="cv", number = 5))
> summary(mod)

Call: rlm(formula = .outcome ~ ., data = dat, psi = psi)
Residuals:
    Min      1Q  Median      3Q     Max
-3.5927 -1.1627 -0.2367  1.2645  5.3572

Coefficients:
            Value   Std. Error t value
(Intercept) 51.6155  5.7235     9.0182
wt          -8.1157  2.1800    -3.7227
cyl         -3.0043  0.9645    -3.1147
hp          -0.0190  0.0105    -1.8026
wtCOLONcyl   0.7446  0.3080     2.4176

Residual standard error: 1.874 on 27 degrees of freedom

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/topepo/caret/issues/526#issuecomment-308543400>, or mute
the thread
