### ISSUE TITLE
findLinearCombos questions

### ISSUE THREAD

**Issue by benjamfield** [topepo/caret#577]
Hello,

I'm playing with some synthetic biological data and when I tested findLinearCombos I found that it recommends removing around 95% of my features. The data consists of several thousand biological pathways. I am hoping to apply feature selection to these pathways. I have a few questions that I suspect have no easy answers:

- generally speaking, when is it appropriate to remove linear combinations? 
- if I remove them, could I be losing important information? could the pathways that form from combinations of other pathways be a better feature than the independent features?
- are there certain models for which it's not recommended to remove linear combinations?

Also, do you have any recommended reading around this topic? 

Thanks!

**Comment by topepo** [comment]
> generally speaking, when is it appropriate to remove linear combinations?

Generally when your model will crash, usually due to `(X'X)`<sup>`-1`</sup>. 

> if I remove them, could I be losing important information? 

Technically no. Since there are other predictors that contain that information, you have no (technical) loss of information. This is why a dummy variable created from a factor with `C` levels only requires `C-1` binary columns. 

However, it could be that the model has more difficulty working since the features don't make it easy for the model to learn the required patterns in the data. 

> could the pathways that form from combinations of other pathways be a better feature than the independent features?

It really depends. For example, suppose you are working on metabolism. Would you like an indictor for "Kerbs cycle" or all of its constituent steps? If only some steps matter for your data, the latter might be appropriate but it might not be that way for your problem. Basically, you would have to try different representations of that data and make that determination empirically (but please do it within a resampling loop)

> are there certain models for which it's not recommended to remove linear combinations?

Yes and it is most of them. Really anything that doesn't directly use the cross-product matrix (like linear regression) should be fine. Even the glmnet or ridge regression could be used since they use regularization to combat this exact problem. I'm partial to tree-based models and these would need no special processing.

**Comment by benjamfield** [comment]
Thanks for the quick and comprehensive reply!
