### ISSUE TITLE
Make theDots available in summaryFunction

### ISSUE THREAD

**Issue by o1iv3r** [topepo/caret#606]
Hi all,

while working on survival type analyses I came across the following issue: theDots is not available in the summaryFunction

Background: The reformulation of a survival problem to a regression problem may require the inclusion of an offset (cf. http://data.princeton.edu/wws509/notes/c7.pdf for details). For example. one may use a Poisson GLM (with or without regularisation) with the log-exposure as an offset. In this case the correct loss function is the deviance (RMSE or R2 are missleading). For example, glmnet also uses the deviance as a performance measure. In order to compute the deviance, one needs to know the offset, which is not available
in summaryFunction; only data, lev and model are. Hence my idea to add theDots to the argument list.

Current Workaround: I'm using weights to hand over the offset. However, this means I have to "customize" each model because an offset is treated differently than a weight.

**Comment by Stevo15025** [comment]
Is this related to #447 ?

**Comment by o1iv3r** [comment]
Thanks Stevo, indeed this seems like a similar issue. I'll check whether the workaround works for me too and if so, post the solution here.

**Comment by topepo** [comment]
I don't think that the dots would help you since, if I'm not mistaken, you need specific data points to compute the offset (i.e. the log of the time variable). You'll need to make sure that the offsets line up with the resampled data. 

This is very similar to issue #478. 

Because of that, the best method for dealing with this in the short term, is to use the offset in the model specification, and deal with it in a summary method.  That's kludgy but for the next few months that is the best approach. 

I'll resolve these issues in the next few months but I'm weighing the pluses and minuses of two methods. I'll be releasing a new package (hopefully next week) that is partially motivated by this issue but it will take a little time to integrate into `caret`.

**Comment by o1iv3r** [comment]
Thanks everyone for their suggestions.

@Stevo15025 Your solution works for me unless I use doparallel (since I am, unfortunately, limited to use R on Windows so that makeForkCluster won't work).

Thus the only practicable solution for me is 
1. to use weights to hand over the offset to the summary function and 
2. to customize the "fit" object of each method so that offset <- wts
(I can post details if someone is interested)

@topepo Which package do you mean? Has it been released already?
I think thedots would help since I can line up the offset using rowIndex (which is Stevo15025's approach, and it works if train is used sequentially)

**Comment by topepo** [comment]
The package is [`recipes`](https://topepo.github.io/recipes/). It should be on CRAN soon.

**Comment by topepo** [comment]
There is a new branch of the package ("recipe_integration") that I hope to merge in within two weeks that uses the [`recipes`](https://topepo.github.io/recipes/) package that can help here. An example of how the code works can be found [here](https://github.com/topepo/caret/commit/ef2ca41e5c341f7506c3361877a1d708e3dd5014#diff-adfc9c815ccf21ae160019a7721fe7da). 

If you take a look please let me know if you see any issues by posting something on the [project page](https://github.com/topepo/caret/projects/1).
