### ISSUE TITLE
Future of Caret

### ISSUE THREAD

**Issue by codingbutstillalive** [topepo/caret#626]
Hi!

I just come from the Webinar on Caret. Max Kuhn there said that he is developing caret for his own work. This statement already dates back quite some time. Before I start with caret, I want to know if this package is still under active development, meaning that it has a future. Could you please comment on that, thanks.

**Comment by topepo** [comment]
Yes. It is [still in development](http://appliedpredictivemodeling.com/blog/2017/2/2/caret-package-plans). I'm putting together a CRAN release now.

**Comment by codingbutstillalive** [comment]
That's good. I am glad to hear that! :)

**Comment by codingbutstillalive** [comment]
One more thing: What's your perspective on the modelr package?

**Comment by topepo** [comment]
I think that Hadely intended it as a basic start on modeling in the tidyverse. They hired my to do something more extensive. There will be some other RStudio packages that overlap with `modelr` in the next year. For example, `modelr` has good tools for splitting data but doesn't really do much on the estimation part that occurs after the holdout results have been generated etc.

**Comment by codingbutstillalive** [comment]
Interesting. You mean, they hired you? 

Yes, today I also read about the pipelearner package. I think that all these efforts are very much appreciated, as Python still has more comfort when it comes to unified interfaces for different modeling aspects. I love it when R is catching up with that.

**Comment by schelhorn** [comment]
If I may offer an opinion:`scikit` may have a more unified API and a larger scope since it also covers unsupervised learning; however, `caret` offers significantly more in terms of supervised learning, in particular specialized models for certain problem domains. 

I guess that reflects the Python versus R way, i.e. computer scientists with a need for elegance vs. statisticians with a need for domain-specific solutions. Things may converge a little on the edges with bipartisan `h2o` and `tensorflow` support, but having a federated mess such as R allows for higher diversity in contributions and specialized syntactical sugar such as pipes. 

Anyways, I'm personally looking forward to full `caret`+`dplyr` integration since I [suggested it to Hadley some time ago](https://twitter.com/schelhorn/status/803512214254735360) ;)

**Comment by topepo** [comment]
For the most part, I agree with @schelhorn's  assessment. 

`pipelearner` is pretty interesting; I'm not completely sure how we will handle the same problem yet but that's one of the things that I'm working on. Delayed/non-standard evaluation can go a long way. 

The tidy versions will be much model modular than `caret`. For example, [recipes](https://github.com/topepo/recipes) is a much more modular and extensible version of `preProcess` that is a lot more ambitious. A number of features will loop back into `caret` too.

**Comment by codingbutstillalive** [comment]
Hi guys,

it's been a while since then. What is the current status on the topics? Especially the marriage of caret and dplyr? ;)

Would be nice to hear from you.
