### ISSUE TITLE
R 3.4.0 Support

### ISSUE THREAD

**Issue by tpletcher** [topepo/caret#669]
Good afternoon,

Just getting going with R, and running through tutorial that depends on caret. Unfortunately it appears 3.4.0 R is not yet supported? Here's output I receive when trying to load via console:

> install.packages("carat")
Warning in install.packages :
  package ‘carat’ is not available (for R version 3.4.0)
> 

Is there a timeframe for support or some type of hack I can use to bypass version checking on install? 

Any guidance / info much appreciated as google searches, etc not returning much in way of this topic.

Cheers,

T

**Comment by topepo** [comment]
Read that one more time and you'll see it: 
```r
install.packages("carat")
Warning in install.packages :
package ‘carat’ is not available (for R version 3.4.0)
```

**Comment by tpletcher** [comment]
ahhh geeez.....i'm going to go bang my head against the wall.....sorry.....

**Comment by topepo** [comment]
No problem =]


On June 19, 2017 at 5:35:58 PM, Tim Pletcher (notifications@github.com)
wrote:

ahhh geeez.....i'm going to go bang my head against the wall.....sorry.....

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/topepo/caret/issues/669#issuecomment-309580651>, or mute
the thread
