### ISSUE TITLE
Ambigious error when the user specifies the data twice 

### ISSUE THREAD

**Issue by SHIMOH** [topepo/caret#680]
Just a pointer for other users and perhaps for the maintainers of the package. Usually caret very diligently points out the mistake the user did by specifying the same argument twice, however this is not the case for the data argument specifically. 
This error could be produced when the user supplies both the "data" argument as well as the x and y arguments: In adaptiveWorkflow(x = x, y = y, wts = weights, info = trainInfo,  :   There were missing values in resampled performance measures.

Some methods can overcome this (e.g., rf), but the majority crash with the aforementioned error. 

Through debugging the error is actually: "formal argument "data" matched by multiple actual arguments".

The obvious fix from the user side is to specifiy only either of the arguments.

**Comment by topepo** [comment]
This is one of the shortcomings of `...` since this could be a valid argument that should be passed to the underlying model function. It's highly unlikely that that "`data`" would be a valid option though. 

At this point, I'm going to avoid putting in a warning or error although I do see the problem. If I did this myself, I would probably spend an hour trying to see the error in my code. On the other hand, that "doh" moment might be more valuable that a formal error message (speaking from my own experience).
