### ISSUE TITLE
names of training variables

### ISSUE THREAD

**Issue by elpidiofilho** [topepo/caret#784]
Hi,
Sometimes I get .RDATA files containing trainings of models using the caret package, made by other people. When I need to predict these models, I need to know the names of the training variables used to fit the model. I found a function caret :: predictors that returns the variables used in the final model but does not work for all models.
 I also discovered that the training dataframe is saved together with the model, so I can use a call like names(fit [[1]]$trainingData) and retrieve this information. 
Would it be possible to implement a function in the caret to return the name of the training variables, which would be more secure against future changes in the caret package?

Thanks

Elpidio

**Comment by topepo** [comment]
`predictors` is not designed to give you all of the column names that were used in the model call. It should give you the names of the predictors that were _functionally dependent_ in the prediction equation. For example, if you fit a CART tree on 1000 predictors but it only splits on two, `predictors` will give you the names of the two variables. 

>  I found a function caret :: predictors that returns the variables used in the final model but does not work for all models.

Can you be more specific about what models do not work?

For _most_ models, there is am object called `xNames` that gives you that list. "Most" is because this is attached to `finalModel` and if the final model is an S4 object, additional variables cannot be attached to it. If you want this for all models, you should use `colnames(fit$trainingData)` and exclude `.outcome`. 

Beware that the results might differ based on _how_ you specify the model (e.g. formula method vs `x`/`y` method). You might get different results (see below). 

```r
> library(caret)
> set.seed(355)
> mod1 <- train(Sepal.Length ~ ., data = iris, method = "rpart")
Warning message:
In nominalTrainWorkflow(x = x, y = y, wts = weights, info = trainInfo,  :
  There were missing values in resampled performance measures.
> predictors(mod1)
[1] "Petal.Length"     "Petal.Width"      "Speciesvirginica" "Sepal.Width"     
> # not availible for all models (excludes those with S4 classes)
> mod1$finalModel$xNames
[1] "Sepal.Width"       "Petal.Length"      "Petal.Width"       "Speciesversicolor" "Speciesvirginica" 
> colnames(mod1$trainingData)
[1] ".outcome"     "Sepal.Width"  "Petal.Length" "Petal.Width"  "Species"     
> 
> set.seed(355)
> mod2 <- train(x = iris[, -1], y = iris$Sepal.Length, method = "rpart")
Warning message:
In nominalTrainWorkflow(x = x, y = y, wts = weights, info = trainInfo,  :
  There were missing values in resampled performance measures.
> predictors(mod2)
[1] "Petal.Length" "Petal.Width"  "Species"      "Sepal.Width" 
> mod2$finalModel$xNames
[1] "Sepal.Width"  "Petal.Length" "Petal.Width"  "Species"     
> colnames(mod1$trainingData)
[1] ".outcome"     "Sepal.Width"  "Petal.Length" "Petal.Width"  "Species" 
```

**Comment by elpidiofilho** [comment]
Help text of caret::predictos 
"The predictors function can be called on the model object (as opposed to the train) object) and the package will try to find the appropriate coed (if it exists).

In cases where the predictors cannot be determined, NA is returned. For example, nnet may return missing values from predictors."


My solution is : varnames = model_list[[i]]$trainingData %>% select(-.outcome)

 thank you by your attention

Elpidio
