### ISSUE TITLE
svmLinear2 can not turn off scale function

### ISSUE THREAD

**Issue by B-Li** [topepo/caret#799]
Hi, when I use train to build a linear svm classification in a toy dataset. It still scales my data when I specified option preProcess = NULL. Could you please check whether this is a bug or tell me what I did wrong? Thank you very much!

**Comment by topepo** [comment]
Can you send a minimal, reproducible example:

__Please read this page__: [reprex = {repr}oducible {ex}ample](https://github.com/jennybc/reprex#what-is-a-reprex) 

Text and example code modified from [the R FAQ on stackoverflow](http://stackoverflow.com/a/5963610)

#### Minimal dataset:
```{R}
library(caret)
set.seed(1)
dat <- twoClassSim(100)
X <- dat[,1:5]
y <- dat[["Class"]]

```
If you have some data that would be too difficult to construct using `caret::twoClassSim` or `caret::SLC14_1`, then you can always make a subset of your original data, using e.g. `head()`, `subset()` or the indices. Then use e.g. `dput()` to give us something that can be put in R immediately, e.g. `dput(head(iris,4))`

If you must use `dput(head())`, please first remove an columns from your dataset that are not necessary to reproduce the error.

If your data frame has a factor with many levels, the `dput` output can be unwieldy because it will still list all the possible factor levels even if they aren't present in the the subset of your data. To solve this issue, you can use the `droplevels()` function. Notice below how species is a factor with only one level: `dput(droplevels(head(iris, 4)))`

#### Minimal, runnable code:
```{R}
model_class <- train(
  X, y, 
  metric='ROC',
  trControl=trainControl(
    method="cv", 
    number=5,
    classProbs=TRUE, 
    summaryFunction=twoClassSummary,
    savePredictions="final")
)
print(model_class)
```

### Session Info:
```{R}
>sessionInfo()

```

You can delete the text in each section that explains how to do it correctly.
Be sure to test your 2 chunks of code in an empty R session before submitting your issue!

**Comment by B-Li** [comment]
My code looks like this:
`dat <- rnorm(2000)
dat <- matrix(dat, ncol = 2)
dat[1:400,] <- dat[1:400,] + 3
dat <- as.data.frame(dat)
dat$label <- rep(c(1,2),times = c(400,600))
colnames(dat) <- c('v1','v2','label')
plot(dat[,1],dat[,2],col = c('blue','red')[dat$label])

library(caret)
set.seed(1)
train.idx <- sample(1000, 500)
dat.train <- dat[train.idx,]
dat.test <- dat[-train.idx,]
# train a model using caret
ctrl <- trainControl(method = 'cv', number = 5)
svm.model <- train(factor(label) ~ ., data = dat.train,
                   method = 'svmLinear2',
                   preProcess = NULL, trainControl = ctrl)
svm.model$finalModel$SV
# train a model using original package
library(e1071)
svm.model.orig <- svm(factor(label) ~ ., data = dat.train,
                      kernel = 'linear', cost = svm.model$finalModel$cost,
                      scale = F)
`
I saw that the SVs given by e1071 was not scaled however the result of caret was scaled.

**Comment by topepo** [comment]
`e1071::svm` defaults `scale` to `TRUE`. If you add this to your `train` call the `...` passes it to `e1071::svm`. 

```r
> ctrl <- trainControl(method = 'cv', number = 5)
> svm.model2 <- train(factor(label) ~ ., data = dat.train,
+                    method = 'svmLinear2',
+                    preProcess = NULL, trainControl = ctrl, scale = FALSE)
> head(svm.model2$finalModel$SV)
          v1       v2
123 2.401114 1.654926
331 1.250212 2.244428
360 1.643696 1.705125
387 1.996129 2.041544
155 1.173023 1.913107
256 1.551083 1.203074
```
