### ISSUE TITLE
Questions over preProcOptions list and preProcess functions

### ISSUE THREAD

**Issue by AndreGuerra123** [topepo/caret#813]
Hello,
1)Does preProcOptions override preProcess options if both are applied in the same train instance?
2)In preProcOptions of trainControl there is a list element ICAcomp, on preProcess of the train we have pcaComp and ICAcomp seems to be missing. (ICAcomp is not an execution parameter of fastICA). Are they equivalents or merge at any point?
3)(Meta-question)Why are the preProcOptions set in the train control?(I see it more as the defining object for sampling, cv, etc..)
Ty for your amazing package, 
André

**Comment by topepo** [comment]
> 1) Does preProcOptions override preProcess options if both are applied in the same train instance?

`preProcOptions` doesn't take the "method" argument so , if I understand the question correctly, they should never be conflicted

> 2) In preProcOptions of trainControl there is a list element ICAcomp, on preProcess of the train we have pcaComp and ICAcomp seems to be missing. (ICAcomp is not an execution parameter of fastICA). Are they equivalents or merge at any point?

`preProcOptions` is there to be more specific about the details of the computations (e.g. the number of components, etc). The `preProcess` option is just a set of operations to do without details (e.g. center the data, do PCA, etc).

> 3)(Meta-question)Why are the preProcOptions set in the train control?(I see it more as the defining object for sampling, cv, etc..)

Poor design =]

Generally, the control objects are there to specific the numeric aspects of the model fit such as the number of iterations and so on. Since `train` does several different distinct things, the extra options are all lumped in there. 

You might consider look at the [`recipes`](https://topepo.github.io/recipes/) package to do your preprocessing with `train`. There are more options, the interface is better, and you can define the order of the steps.
