### ISSUE TITLE
rf_fit$finalModel, why need finalModel

### ISSUE THREAD

**Issue by fiona-wang** [topepo/caret#814]
I use the 

rf_fit <- train(x,y,method="rf", ntree=ntree,metric=metric)
Pred1 <-predict(rf_fit,type='prob')

Pred2 <-predict(rf_fit$finalModel,type='prob')

Question, why in the this case, we need to use the "rf_fit$finalModel"?

**Comment by topepo** [comment]
You don't. Jus predict with `rf_fit`. Please **don't** use the `finalModel` object. You can get the wrong answers that way.

**Comment by kmishra9** [comment]
I get dramatically different results (much better without using the `finalModel` object), but I'm wondering _why_ it is that the predictions vary? 

Then, when I fit the same model with the bestTune paramaters by hand, I get identical results to when I predict using finalModel, rather than the best performance from `predict` by itself. Why?
