### ISSUE TITLE
Feature Request: selectionFunction per timeslice

### ISSUE THREAD

**Issue by amanka** [topepo/caret#864]
For backtesting, it would be nice to apply the `selectionFunction` in `trainControl` per timeslice. This could then be combined with `savePredictions = "best"`. The result would be a set of predictions that could have been made historically.

**Comment by topepo** [comment]
That wouldn't work since the selection function would/could generate a different tuning parameter per resample. I'm not sure how it would create `finalModel`. 

You could achieve the same thing by using `returnResamp = "all"` then manually applying the selection function over time slices. That would at least tell you what it would have chosen at each point. Alternatively, you could do the same using `savePredictions` too.

**Comment by amanka** [comment]
Thanks. That is a good point. With backtesting though, the `finalModel` could still be whatever the `selectionFunction` would normally pick. The only issue is using predictions from a finalModel that would not have been selected at some historical date.

However, this would be a bit hacky, saving predictions that aren't from the finalModel.

`oneSE()` and `best()` expect a data-frame pre-sorted by complexity. Are the results from a `train` object's `my.train$results` predictions sorted in this way? It looks like the [sort](https://topepo.github.io/caret/using-your-own-model-in-train.html#Components) element is relevant here.
