### ISSUE TITLE
How to limit the number of sub-processes created by caret::train ?

### ISSUE THREAD

**Issue by ldesousa** [topepo/caret#870]
I am having a hard time to train gradient boost with a large regression matrix that takes about 2 GB of memory. I initially thought it was an issue with the `doParallel` package [failing to restrict the number of "cores" available to the `train` function](https://stackoverflow.com/q/49852556/2066215). However, I have tried it with other parallelisation packages and the result is always the same: the number of back end sub-process is always a multiple of the CPUs available in the workstation, inevitably leading to memory exhaustion and the consequent crash.

Therefore I now suspect that these sub-process are being created by the `train` function itself. Could this be the case? if yes, how can restrict its number to, say, 8?

**Comment by topepo** [comment]
What code are you running (and session info etc)? 

I can't imagine why it would spawn more workers unless you are doing a lot of nested modeling and each level uses parallelism (using `rfe` or `gafs`). Most of the functions that use parallelism have an `allowParallel` option to stop the parallel backend from exponentially creating workers.

**Comment by ldesousa** [comment]
Here is a clean version of the model fitting script:

```
library(caret)
library(xgboost)

source("saveRDS_functions.R")

## Load datasets
formulaString <- readRDS.gz("formulaString.rds")
dfs <- readRDS(paste0("dfs.rds"))
ctrl <- readRDS.gz("ctrl.rds")
tuneGrid <- readRDS.gz("tuneGrid.rds")

## Model fitting
mgbX <- caret::train(formulaString, data=dfs, method="xgbTree", trControl=ctrl, tuneGrid=gb.tuneGrid) 
cat(paste0(Sys.time(), " : Ended caret training with xgbTree\n"), file=out.file, append=TRUE)
saveRDS.gz(mgbX, file=paste0("mgb.MY_VAR.rds"))
## save binary model for prediction:
xgb.save(mgbX$finalModel, paste0("Xgb.MY_VAR.rds"))

## Print out model
importance_matrix <- xgb.importance(mgbX$coefnames, model = mgbX$finalModel)
out.file = paste0("MY_VAR_resultsFitGradientBoost.ex_nl.txt")
cat("Results of model fitting 'XGBoost':\n\n", file=out.file)
cat("\n", file=out.file, append=TRUE)
print(mgbX)
cat("\n XGBoost variable importance:\n", file=out.file, append=TRUE)
print(importance_matrix[1:25,])
cat("--------------------------------------\n", file=out.file, append=TRUE)
```

I run it on a fresh session and load the required data from disk, to guarantee minimum RAM usage.

How can I use `allowParallel` with the `caret::train` function?

**Comment by hadjipantelis** [comment]
@ldesousa Unfortunately the code you present is not a reproducible example. 


That said, I think that part of the problem experienced is due to XGBoost's OpenMP spawning multiple procedures itself. That way (assuming a 4-core machine) we have 4 multi-threaded OpenMP processes trying to run on  4 cores and creating a race condition among themselves. Given that you use XGBoost consider *not* using explicitly parallelism through `caret` but allowing XGBoost to use all the cores on your system. 

In general, as XGBoost uses OpenMP to parallelise its computations  and most parallelism packages in R  are agnostic to what their underlying procedure try to do, mix-ups are to be expected...  You might want to consider running 
```R
mgbX <- caret::train(formulaString, data=dfs, method="xgbTree", trControl=ctrl,
                     tuneGrid=gb.tuneGrid, nthread = 1) 
```
and see where this gets you. This will set the number of thread used in training to 1 and thus (hopefully) alleviate part of your problem. (But as mentioned, first consider allowing XGBoost to parallelise its computations itself.)

**Comment by topepo** [comment]
Since your are using `xgboost`, @hadjipantelis i right on the money. 

If you are tuning the model, you would be better off parallelizing the resamples than to use the threading in each model fit. See [this blog post](http://appliedpredictivemodeling.com/blog/2018/1/17/parallel-processing) for some benchmarks (esp the ones at the end).

**Comment by ldesousa** [comment]
@hadjipantelis Thank you, that is what I was looking for. The `nthread` argument is not present in the documentation (version 6.0.79), therefore I will leave this issue open.

Another thing, I am not using parallelism explicitly (if I read you correctly), not even importing the libraries. Therefore the process spawning must be all the responsibility of `caret::train` (or whatever other functions it may be invoking). 

@topepo I can spend some time developing a reproducible example, if it is useful. The only special thing is the regression matrix. 

Also, parallelising the resamples should lead to process spawning at multiple levels, thus resulting in over a hundred process in this 12 CPU architecture.

**Comment by hadjipantelis** [comment]
@ldesousa Cool, I am glad I could help. (Side-note: I am uncertain why would the `nthread` argument be relevant in `caret`'s documentation; `nthread` is a XGBoost parameter that does not directly affect the estimated values. We access it through the ellipsis (`...`).

**Comment by topepo** [comment]
The threading for `xgboost` isn't well documented. 

The [help documents](http://xgboost.readthedocs.io/en/latest/parameter.html) has 

> `nthread` [default to maximum number of threads available if not set]

You'll have to set `nthread = 1` in the `train` call to stop the threading parallelism. 

Also, just to make sure that `train` isn't going to parallelize, you can use `trainControl(allowParallel = FALSE)`.

**Comment by ldesousa** [comment]
Hello again. I just opened [a thread at xgboost-user](https://groups.google.com/forum/#!forum/xgboost-user) that might be related to this question. Basically, I can now control the number of sub-processes launched in training, but they just suck up memory to oblivion. This is likely not related to `caret` but I leave it here for reference.

**Comment by topepo** [comment]
I'd suggest opening a new issue if you think that it is a separate problem. 

Also, that group is members only (and I won't join just to see the discussion) so can you give us some details on the current issue (and the discussion)?

**Comment by ldesousa** [comment]
@topepo This is indeed a different issue. The number of CPUs question, while important, is actually not at the root of my problems. Issue #880 reports the details.
