### ISSUE TITLE
glmnet with poisson family

### ISSUE THREAD

**Issue by cmac77** [topepo/caret#876]
Hi,

Does caret not support Poisson regression through glmnet? When I checked glmnet through model info, it looks like 'gaussian', 'binomial', and 'multinomial' families are supported. But I wanted to double check here to make sure that I am not overlooking something. I can run the train function using glmnet and 
specifying "family = poisson", but the values returned are N/A.

Thank you in advance for any information!

Chris

**Comment by topepo** [comment]
It works for me:

```r
library(caret)

set.seed(1455)
mod <- train(breaks ~ ., data = warpbreaks,
             method = "glmnet",
             family = "poisson")
```

Please follow the issue template and give enough details to figure out the issues.

**Comment by ariKoi** [comment]
In
`mod$modelInfo$grid`
the poisson family does not seem to be considered.

If you in addition save the predictions :
```
library(tidyverse)
library(caret)
library(glmnet)

set.seed(1455)
mod <- train(breaks ~ ., data = warpbreaks, 
trControl = trainControl(savePredictions=TRUE), 
method = "glmnet", family = "poisson")
```
and look at the predictions of the optimal model:

`as_tibble(mod$pred) %>% 
mutate(lambda = round(lambda, digits = 3)) %>% 
filter(alpha == 0.1, lambda == 0.917)`

the pred and obs are on a different scale e.g.
`xyplot(pred~obs, data = as_tibble(mod$pred) %>% 
mutate(lambda = round(lambda, digits = 3)) %>% 
filter(alpha == 0.1, lambda == 0.917))`

So it looks like predict.train is using the default type = "link" argument (i.e. linear predictor) instead of type = "response" (i.e. the fitted mean) in predict.glmnet.

A quick & dirty solution might be to exponentiate the predictions, and then compare with the actual counts.

**Comment by topepo** [comment]
This is a good idea. 

Unfortunately, `caret` is at the lifecycle point of having a fairly complete interface, so this isn't a good fit.  

The development work is focused on squashing bugs and any changed required by the underlying model packages.
