### ISSUE TITLE
adding ntree as a parameter in rf

### ISSUE THREAD

**Issue by colorlace** [topepo/caret#886]
Is there any disincentive to adding this feature? I would sure like to see it. Not to mention it is an input in the basic randomForest function.

**Comment by colorlace** [comment]
Is there any disincentive to adding this feature? I would sure like to see it. Not to mention it is an input in the basic randomForest function.

**Comment by topepo** [comment]
You can pass it to `randomForest` by passing the argument to `train`. 

I didn't include it because I don't see it as a tuning parameter; it only controls the precision on the model and, if you set it to a few thousand, you get a stable model. 

At this point, it would break a lot of existing code to include it. 

You can always create your own [custom method](https://topepo.github.io/caret/using-your-own-model-in-train.html) do use it though.

**Comment by colorlace** [comment]
I didn't realize you could pass it through `train`. That's great. Thanks!
