### ISSUE TITLE
Convert random forest model into C++ code

### ISSUE THREAD

**Issue by Victsz** [topepo/caret#916]
I`m wondering If there is a proper practice to convert a random forest output model into c++ code.

We could implement the code manually but which is really hard to maintain a large forest of if-else statement. And it would be really hard to do the unit test.

Thanks a lot.

**Comment by zachmayer** [comment]
Use the ranger package: https://cran.r-project.org/web/packages/ranger/index.html

It's already supported in caret

**Comment by zachmayer** [comment]
Sorry, I misunderstood.  I thought you wanted a faster random forest package, which ranger provides.

There's tools in R to covert a random forest to PMML.  You could then look for a tool to import the PMML into C++

**Comment by Victsz** [comment]
@zachmayer thanks
Yes, I tried googling PMML and C++. But only found a PMML importer for Java.

**Comment by Victsz** [comment]
em...but I feel really great to do training in caret ...just dont know how to deploy to the production.

**Comment by zachmayer** [comment]
Once you've chosen the model in caret, you can save the dataset to a csv, and then use the hyperparameters from caret to train the model in C++

**Comment by topepo** [comment]
About 10 yrs ago, I wrote some code to take a `randomForest` object and write out the rules in C. It wasn't a great idea because the smallest model that I made had a compiled object that was 100MB. 

A better idea would be to write the split information in some sort of flat file then write C to loop over rows of it... which is exactly what [Cubist](https://www.rulequest.com/cubist-unix.html#HOOKS) and [C5.0](https://www.rulequest.com/see5-unix.html#HOOKS) do. If you use those R packages, you can tune in `caret` and write out the file when you are done.

**Comment by Victsz** [comment]
@topepo thank you for the sharing.
I will take a look.
