### ISSUE TITLE
confusion matrix different from finalModel and predict on training set

### ISSUE THREAD

**Issue by Victsz** [topepo/caret#917]
My training final model has a very different confusion matrix with the result I use predict on training set.
Could some one point out to me where is the problem?
![image](https://user-images.githubusercontent.com/8154646/42979080-e6c7a1b4-8c02-11e8-973e-931d1499251d.png)

Code:
dTesting[,D:=factor(D, levels=c("P","N") )] 
tc<-trainControl( method='none',allowParallel = F,classProbs = F)
dModelFit <- train(D~.,data=dTraining,method="rf",prox=F,trControl =tc)

pred <- factor( predict(dModelFit,dTraining),levels=c("P","N") )
re<-table(pred,dTraining$D)
confusionMatrix(re)

**Comment by Victsz** [comment]
https://stats.stackexchange.com/questions/109079/confusion-between-caret-randomforest-predict-results-and-reported-model-perfor
I found a similar question from stackexchange

**Comment by topepo** [comment]
You are pre-predicting the training set in your code that uses `confusionMatrix`. For a model like random forest, it is common to get perfect performance when doing this (which is why it is a bad idea). The OOB estimate should be much closer to the estimate that `train` would would give with a different `method` argument to `trainControl`
