### ISSUE TITLE
Negative gcv values in varImp when using earth

### ISSUE THREAD

**Issue by Ranae** [topepo/caret#926]
I updated the `earth` package today and also saw some negative gcv values when using varImp (same in earth::evimp). I see in the documentation that "Negative variable importance values for MARS are set to zero", but they didn't seem to be in this case.

I will post a reproducible example when I get the time tomorrow, but maybe it is not necessary?

**Comment by topepo** [comment]
If you have one, please send. You might contact Steve though; it sounds like an underlying `earth` issue. However, `caret` should deal with that better. 

It is possible to get a negative GCV value. `earth` uses the CGV version of `R^2` and, if you use the traditional linear regression `R^2` equation, it can be negative for really poor models (no offense) and/or small sample sizes. That's why `caret` uses the correlation statistic squared.

**Comment by topepo** [comment]
Any movement on this with the `earth` package?

**Comment by Ranae** [comment]
I can't replicate it with my code from that day. It might be that I didn't commit the problem code, but I haven't run into the issue since then. I think we can consider it closed. I will bring it up again (and save the code) if I see it again.
