### ISSUE TITLE
Confusion matrix error

### ISSUE THREAD

**Issue by ronencozen** [topepo/caret#947]
Hello,

I am asking for the confusion matrix using the following line:

`confusionMatrix(cart.model, test$meet_kpi, positive='No')`

and get the following error:

> Error in match.arg(norm, c("none", "overall", "average")) : 
  'arg' must be NULL or a character vector

I would like to find out what is the nature of this error,  what is the complaint.

Thanks in advance,

Ronen

**Comment by ronencozen** [comment]
problem solved.

**Comment by jacksontorreseconomista** [comment]
Hi, can you show how did you solve this problem? I have de same

**Comment by cramezan** [comment]
> 

He was predicting on his model in the confusion matrix, rather than the prediction itself.  I just ran into error this myself.

For my code which produced the error:

svm.model001 <- train(class_name~., data=Train001, method = "svmRadial", 
                      tuneLength = 10,
                      preProcess = c("center", "scale"),
                      trControl = trainctrl,
                      metric="Kappa")

svm.predict001 <-predict(svm.model001, DelTest, verboseIter = TRUE)
confusionMatrix(svm.model001, as.factor(DelTest$class_name))

The issue is in the confusionMatrix line.  It should read my stored prediction variable instead of the model variable.
**confusionMatrix(svm.predict001, as.factor(DelTest$class_name))**

**Comment by niharikakotaru** [comment]
> > 
> 
> He was predicting on his model in the confusion matrix, rather than the prediction itself. I just ran into error this myself.
> 
> For my code which produced the error:
> 
> svm.model001 <- train(class_name~., data=Train001, method = "svmRadial", tuneLength = 10, preProcess = c("center", "scale"), trControl = trainctrl, metric="Kappa")
> 
> svm.predict001 <-predict(svm.model001, DelTest, verboseIter = TRUE) confusionMatrix(svm.model001, as.factor(DelTest$class_name))
> 
> The issue is in the confusionMatrix line. It should read my stored prediction variable instead of the model variable. **confusionMatrix(svm.predict001, as.factor(DelTest$class_name))**

Thank you so much! it worked
