### ISSUE TITLE
Predict using only features selected in a final model

### ISSUE THREAD

**Issue by wvictor14** [topepo/caret#968]
Hi, I have built a model using caret which I would like to distribute. The final model uses less features than the features inputted as training data. Ideally, users could input new data with only the subset of features used in the final model. This is desirable because the original number of features is many many times larger than the final features. However, I notice 'predict()' will require all training features to present in any new sample to be ran on. To this end, I fiddled around trying to extract the components of the modelFit object (e.g. modelFit$Finalmodel) for quite awhile, with no success. I hope it is ok to post this as an 'issue', but I would appreciate direction to the proper forum if this is not it.

Below I post the development of a glmnet model, and then the ideal code a user would have to execute to get predictions on data with only features used in the final model. 

```{R}
# training data
library(caret)
set.seed(1)
dat <- twoClassSim(100, noiseVars = 5)
X <- dat[,1:20]
y <- dat[["Class"]]

# fit glmnet model
glm_fit <- train(
  X, y, 
  metric='ROC',
  method = 'glmnet',
  trControl=trainControl(
    method="cv", 
    number=5,
    classProbs=TRUE, 
    summaryFunction=twoClassSummary,
    savePredictions="final")
)

length(predictors(glm_fit)) 
ncol(X) # 15 / 20 variables in final model

# predict on new samples, where only the 15 variables used in the final model are present
set.seed(2)
newDat <- twoClassSim(100, noiseVars = 5)
newDat_subset <- newDat[,predictors(glm_fit)] # subset out 15 final predictors
dim(newDat_subset) # 100 15

predict(glm_fit, newDat_subset) # error
```

**Comment by topepo** [comment]
This is a big problem overall and it difficult to change for a few reasons. 

Here's an example: if you fit a regression tree on thousands of predictors and the model selects three, you like to only have three required. However, all of the standard R infrastructure (think `model.matrix`) and most C and R code are geared towards the entire predictor set. As an example, some C code references the predictors by their location/index rather than their name. If we eliminate predictors, those indices would have to be updated along with any other associated components. 

Another issue is that you might not get the same model if you refit with the smaller predictor set. MARS is a good example of this because it uses the degrees of freedom in the selection process; it wouldn't have the same selection process if it were just given the selected predictors.  This also highlights that the change probably needs to happen at the package level (and not the `caret`-level, but see comments below*)

For `glmnet`, I have seen people do optimization on the full predictor set with L1 and L2 penalties and then fitting a secondary L2 only model on the selected set. Also, if you just want prediction, just get the coefficients and do the cross-produce with the sample vector (ugly but doable). 

*I do have a longer term goal of being able to _extract_ the prediction function from R models so that they can be easily put into production (perhaps without R and using tenorflow). I'm going to start working on that in earnest next year but, in the meantime, take a look at the [`tidypredict`](https://tidypredict.netlify.com/) package. It can translate some model's prediction code to SQL. It does linear models but I'm not sure about `glmnet`. If it doesn't, put in an issue and reference this one. I might be able to talk Edgar into prioritizing `glmnet` since it is very popular.

**Comment by wvictor14** [comment]
Thanks for the timely and thorough response. 

Yes, I think for some models it would be nice to enable this feature, but can understand the issues it might create for other algorithms such as MARS.

I think for now I'll implement a lazy workaround by adding in all-zero variables corresponding to the missing but non-essential features. At least for my purposes and with respect to the potential indexing issue you mention, I think this will work.
